participar:
    pattern: /ajax/participar
    defaults: { _controller: LoogaresBlogBundle:Default:participar }
actualizar_participantes:
    pattern: /ajax/actualizar_participantes
    defaults: { _controller: LoogaresBlogBundle:Default:actualizarParticipantes }

post_sin_ciudad:
    pattern:  /blog/{slug}
    defaults: { _controller: LoogaresBlogBundle:Default:post, ciudad: null }

post:
    pattern:  /{ciudad}/blog/{slug}
    defaults: { _controller: LoogaresBlogBundle:Default:post, ciudad: null }

concurso_registro:
    pattern:  /{ciudad}/blog/{slug}/concurso/registro
    defaults: { _controller: LoogaresBlogBundle:Default:registroPopUp, ciudad: null }

concurso_compartir:
    pattern:  /{ciudad}/blog/{slug}/concurso/compartir/{tipo}
    defaults: { _controller: LoogaresBlogBundle:Default:compartirPopUp, ciudad: null }

blog:
    pattern:  /{ciudad}/blog
    defaults: { _controller: LoogaresBlogBundle:Default:index }