post:
    pattern:  /{ciudad}/blog/{slug}
    defaults: { _controller: LoogaresBlogBundle:Default:post, ciudad: null }

blog:
    pattern:  /{ciudad}/blog
    defaults: { _controller: LoogaresBlogBundle:Default:index }
