Loogares\UsuarioBundle\Entity\Dueno:
    type: entity
    table: duenos
    manyToOne:
        lugar:
            targetEntity: Loogares\LugarBundle\Entity\Lugar
        estado:
            targetEntity: Loogares\ExtraBundle\Entity\Estado
    id:
        id:
            type: integer
            generator: { strategy: auto }

    fields:
        nombre:
            type: string
        apellido:
            type: string
        mail:
            type: string
        telefono:
            type: string
        texto:
            type: text
        fecha:
            type: datetime