Loogares\UsuarioBundle\Entity\EstadoRecomendacion:
    type: entity
    table: estado_recomendacion
    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        nombre:
            type: string