Loogares\UsuarioBundle\Entity\LoogarenoEstrella:
    type: entity
    table: loogareno_estrella
    oneToOne:
        recomendacion:
            targetEntity: Loogares\UsuarioBundle\Entity\Recomendacion
    id:
        id:
            type: integer
            generator: { strategy: auto }

    fields:
        detalle:
            type: text
        fecha:
            type: datetime