Loogares\UsuarioBundle\Entity\Recomendacion:
    type: entity
    table: recomendacion
    repositoryClass: Loogares\UsuarioBundle\Repository\RecomendacionRepository
    manyToOne:
        lugar:
            targetEntity: Loogares\LugarBundle\Entity\Lugar
            joinTable:
                name: recomendacion
                joinColumns:
                    lugar:
                        referencedColumnName: id
        usuario:
            targetEntity: Loogares\UsuarioBundle\Entity\Usuario
            joinTable:
                name: recomendacion
                joinColumns:
                    usuario:
                        referencedColumnName: id
        estado:
            targetEntity: Loogares\ExtraBundle\Entity\Estado
            joinTable:
                name: recomendacion
                joinColumns:
                    estado:
                        referencedColumnName: id
    oneToMany:
        util:
            targetEntity: Loogares\UsuarioBundle\Entity\Util
            mappedBy: recomendacion
        tag_recomendacion:
            targetEntity: Loogares\UsuarioBundle\Entity\TagRecomendacion
            mappedBy: recomendacion
            onDelete: cascade
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        texto:
            type: text
        estrellas:
            type: float
        precio:
            type: integer
        fecha_creacion:
            type: datetime
        fecha_ultima_modificacion:
            type: datetime
        fecha_ultima_vez_destacada:
            type: date
            nullable: true