Loogares\UsuarioBundle\Entity\Tag:
    type: entity
    table: tag
    oneToMany:
        tag_recomendacion:
            targetEntity: Loogares\UsuarioBundle\Entity\TagRecomendacion
            mappedBy: recomendacion
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        tag:
            type: string
        slug:
            type: string