Loogares\UsuarioBundle\Entity\TipoUsuario:
    type: entity
    table: tipo_usuario
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        nombre:
            type: string
        descripcion:
            type: string