Loogares\UsuarioBundle\Entity\Usuario:
    type: entity
    repositoryClass: Loogares\UsuarioBundle\Repository\UsuarioRepository
    table: usuarios
    manyToOne:
        tipo_usuario:
            targetEntity: Loogares\UsuarioBundle\Entity\TipoUsuario
        estado:
            targetEntity: Loogares\ExtraBundle\Entity\Estado
        pais:
            targetEntity: Loogares\ExtraBundle\Entity\Pais
        ciudad:
            targetEntity: Loogares\ExtraBundle\Entity\Ciudad
        comuna:
            targetEntity: Loogares\ExtraBundle\Entity\Comuna

    oneToMany:
        recomendaciones:
            targetEntity: Loogares\UsuarioBundle\Entity\Recomendacion
            mappedBy: usuario
        descuentos_usuarios:
            targetEntity: Loogares\CampanaBundle\Entity\DescuentosUsuarios
            mappedBy: usuario
        participantes:
            targetEntity: Loogares\BlogBundle\Entity\Participante
            mappedBy: usuario
        reportar_lugar:
            targetEntity: Loogares\LugarBundle\Entity\ReportarLugar
            mappedBy: usuario

    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        nombre:
            type: string
        apellido:
            type: string
        password:
            type: string
            length: 40
        sha1password:
            type: string
            length: 40
            nullable: true
        slug:
            type: string
        mail:
            type: string
        telefono:
            type: string
            nullable: true
        sexo:
            type: string
            nullable: true
        web:
            type: string
            nullable: true
        facebook:
            type: string
            nullable: true
        twitter:
            type: string
            nullable: true
        imagen_full:
            type: string
        fecha_nacimiento:
            type: datetime
            nullable: true
        mostrar_edad:
            type: boolean
            nullable: true
        fecha_registro:
            type: datetime
        fecha_ultima_actividad:
            type: datetime
            nullable: true
        newsletter_activo:
            type: boolean
        hash_confirmacion:
            type: string
            length: 40
            nullable: true
        cookie:
            type: string
            nullable: true
        facebook_uid:
            type: integer
            nullable: true
        facebook_no_publicar:
            type: smallint
            nullable: true
        facebook_data:
            type: string
            nullable: true
        fecha_facebook_ultima_actividad:
            type: datetime
            nullable: true
        salt:
            type: string
    indexes:
        idx_usuarios_slug:
            columns: ["slug"]

    lifecycleCallbacks:
        preUpdate: [ preUpload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]