Loogares\UsuarioBundle\Entity\Usuario:
    type: entity
    repositoryClass: Loogares\UsuarioBundle\Repository\UsuarioRepository
    table: usuarios
    manyToOne:
        tipo_usuario:
            targetEntity: TipoUsuario
    manyToOne:
        comuna:
            targetEntity: Loogares\ExtraBundle\Entity\Comuna
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        nombre:
            type: string
            length: 50
        apellido:
            type: string
        usuario:
            type: string
        password:
            type: string
            legnth: 40
        slug:
            type: string
        mail:
            type: string
        telefono:
            type: string
            nullable: true
        sexo:
            type: string
            nullable: true
        link1: 
            type: string
            nullable: true
        link2:
            type: string
            nullable: true
        link3:
            type: string
            nullable: true
        imagen_full:
            type: string
        fecha_nacimiento:
            type: datetime
            nullable: true
        fecha_registro:
            type: datetime
        fecha_ultima_actividad:
            type: datetime
        confirmado:
            type: integer
        newsletter_activo:
            type: smallint
        hash_confirmacion:
            type: string
            length: 40
        cookie:
            type: string
        facebook_uid:
            type: integer
            nullable: true
        facebook_no_publicar:
            type: integer
            nullable: true
        facebook_data:
            type: string
            nullable: true
        fecha_facebook_ultima_actividad:
            type: string
            nullable: true
