Loogares\UsuarioBundle\Entity\Util:
    type: entity
    table: util
    manyToOne:
        recomendacion:
            targetEntity: Loogares\UsuarioBundle\Entity\Recomendacion
            joinTable:
                name: util
                joinColumns:
                    recomendacion:
                        referencedColumnName: id
            inversedBy: recomendacion
        usuario:
            targetEntity: Loogares\UsuarioBundle\Entity\Usuario
            joinTable:
                name: util
                joinColumns:
                    usuario:
                        referencedColumnName: id
    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        fecha:
            type: datetime