registroUsuario:
    pattern: /registro
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:registro }

confirmarUsuario:
    pattern:  /confirmar/{hash}
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:confirmar }

olvidarPassword:
    pattern:  /olvidar_password
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:olvidarPassword }

regenerarPassword:
    pattern:  /regenerar_password/{hash}
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:regenerarPassword }

login:
    pattern:   /
    defaults:  { _controller: LoogaresUsuarioBundle:Usuario:login }    
    
login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

showUsuario:
    pattern:  /{param}
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:show }

actividadUsuario:
    pattern:  /{param}/actividad
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:actividad }


recomendacionesUsuario:
    pattern:  /{param}/recomendaciones
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:recomendaciones }

fotosLugaresUsuario:
    pattern:  /{param}/fotos
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:fotos }

lugaresUsuario:
    pattern:  /{param}/lugares
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:lugares }

editarUsuario:
    pattern:  /{param}/editar
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:editar }

editarCuentaUsuario:
    pattern:  /{param}/editar/cuenta
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:editarCuenta }

editarFotoUsuario:
    pattern:  /{param}/editar/foto
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:editarFoto }

editarPasswordUsuario:
    pattern:  /{param}/editar/password
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:editarPassword }

editarBorrarUsuario:
    pattern:  /{param}/editar/borrar
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:editarBorrar }

accionesPendientes:
    pattern:  /acciones_pendientes/{accion}
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:totalAccionesPendientes }