LoogaresUsuarioBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:index }

registroUsuario:
    pattern: /registro
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:registro }

confirmarUsuario:
    pattern:  /confirmar/{hash}
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:confirmar }

login:
    pattern:   /{_locale}
    defaults:  { _controller: LoogaresUsuarioBundle:Usuario:login, _locale: es }
    requirements:
        _locale: es|en

login_translated:
    pattern:   /
    defaults:  { _controller: LoogaresUsuarioBundle:Usuario:login }
    
    
login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

showUsuario:
    pattern:  /{param}
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:show }

actividadUsuario:
    pattern:  /{param}/actividad
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:actividad }


recomendacionesUsuario:
    pattern:  /{param}/recomendaciones
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:recomendaciones }


