registroUsuario:
    locales:
        es: /usuario/registro
        en: /user/signup
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:registro }

confirmarUsuario:
    locales:
        es: /usuario/confirmar/{hash}
        en: /user/confirm/{hash}
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:confirmar }

olvidarPassword:
    locales:
        es: /usuario/olvidar_password
        en: /user/forget_password
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:olvidarPassword }

regenerarPassword:
    locales:
        es: /usuario/regenerar_password/{hash}
        en: /user/regenerate_password/{hash}
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:regenerarPassword }

login:
    locales:
        es: /usuario
        en: /user
    defaults:  { _controller: LoogaresUsuarioBundle:Usuario:login }

login_check:
    locales:
        es: /usuario/login_check
        en: /user/login_check
    defaults:  { _controller: LoogaresUsuarioBundle:Usuario:loginCheck }

login_check_facebook:
    locales:
        es: /usuario/login_check_facebook
        en: /user/login_check_facebook
    defaults:  { _controller: LoogaresUsuarioBundle:Usuario:loginCheckFacebook }

logout:
    locales:
        es: /usuario
        en: /user
    pattern:   /logout

forzarDatosUsuario:
    locales:
        es: /usuario/forzar_datos
        en: /user/force_data
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:forzarDatos }

showUsuario:
    locales:
        es: /usuario/{param}
        en: /user/{param}
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:show }

actividadUsuario:
    locales:
        es: /usuario/{param}
        en: /user/{param}
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:actividad }

actividadUsuario_total:
    locales:
        es: /usuario/{param}/actividad
        en: /user/{param}/activity
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:actividad, actividad_total: true }

recomendacionesUsuario:
    locales:
        es: /usuario/{param}/recomendaciones
        en: /user/{param}/reviews
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:recomendaciones }

fotosLugaresUsuario:
    locales:
        es: /usuario/{param}/fotos
        en: /user/{param}/photo
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:fotos }

lugaresUsuario:
    locales:
        es: /usuario/{param}/lugares/{accionLugar}
        en: /user/{param}/places/{accionLugar}
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:lugares, accionLugar: visitar }

cuponesUsuario:
    locales:
        es:  /{param}/cupones/{tipo}
        en:  /{param}/coupons/{tipo}
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:cupones }

inprimirCuponUsuario:
    locales:
        es: /usuario/{param}/cupones/{tipo}/{cupon}/imprimir
        en: /user/{param}/coupons/{tipo}/{cupon}/print
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:imprimirCupon }

editarUsuario:
    locales:
        es: /usuario/{param}/editar
        en: /user/{param}/edit
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:editar }

editarCuentaUsuario:
    locales:
        es: /usuario/{param}/editar/cuenta
        en: /user/{param}/edit/account
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:editarCuenta }

editarFotoUsuario:
    locales:
        es: /usuario/{param}/editar/foto
        en: /user/{param}/edit/photo
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:editarFoto }

editarPasswordUsuario:
    locales:
        es: /usuario/{param}/editar/password
        en: /user/{param}/edit/password
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:editarPassword }

editarNotificacionesUsuario:
    locales:
        es: /usuario/{param}/editar/notificaciones
        en: /user/{param}/edit/notifications
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:editarNotificaciones }

editarConexionesUsuario:
    locales:
        es: /usuario/{param}/editar/conectar
        en: /user/{param}/edit/connect
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:editarConexiones }

editarBorrarUsuario:
    locales:
        es: /usuario/{param}/editar/borrar
        en: /user/{param}/edit/delete
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:editarBorrar }

accionesPendientes:
    locales:
        es: /usuario/acciones_pendientes/{accion}
        en: /user/pending_actions/{accion}
    defaults: { _controller: LoogaresUsuarioBundle:Usuario:totalAccionesPendientes }