parameters:
#    loogares_usuario.example.class: Loogares\UsuarioBundle\Example

services:
#    loogares_usuario.example:
#        class: %loogares_usuario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
