Loogares\UsuarioBundle\Entity\Usuario:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: 'mail'
            message: "usuario.errors.validacion.mail.unico"
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: 'slug'
            message: "usuario.errors.validacion.slug.unico"
    properties:
        mail:
            - NotBlank:
                message: usuario.errors.validacion.mail.blanco
            - Email: { message: "usuario.errors.validacion.mail.invalido" }
        password:
            - NotBlank:
                message: usuario.errors.validacion.password.blanco
            - MinLength: { limit: 6, message: "usuario.errors.validacion.password.minimo" }
        nombre:
            - NotBlank:
                message:  usuario.errors.validacion.nombre.blanco
            - Type: { type: string, message: "usuario.errors.validacion.nombre.tipo" }
        apellido:
            - NotBlank:
                message: usuario.errors.validacion.apellido.blanco
            - Type: { type: string, message: "usuario.errors.validacion.apellido.tipo" }
        #slug:
         #   - NotBlank:
          #      message: usuario.errors.validacion.slug.blanco
           # - Type: { type: string, message: "usuario.errors.validacion.slug.tipo" }
        file:
            - Image:
                maxSize: 5120k
                mimeTypesMessage: usuario.errors.validacion.imagen.tipo

Loogares\UsuarioBundle\Entity\Dueno:
    properties:
        nombre:
            - NotBlank:
                message: dueno.errors.validacion.nombre.blanco
        apellido:
            - NotBlank:
                message: dueno.errors.validacion.apellido.blanco
        mail:
            - NotBlank:
                message: dueno.errors.validacion.mail.blanco
        telefono:
            - NotBlank:
                message: dueno.errors.validacion.telefono.blanco
        texto:
            - NotBlank:
                message: dueno.errors.validacion.texto.blanco