Loogares\UsuarioBundle\Entity\Usuario:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: 'mail'
            message: "La dirección de E-mail está repetida. Por favor, prueba con otra."
    properties:
        mail:
            - NotBlank:
                message: El campo E-mail no puede ser vacío.
            - Email: { message: "Email inválido." }
        password:
            - NotBlank:
                message: El campo Password no puede ser vacío.
            - MinLength: { limit: 6, message: "El password debe tener un mínimo de {{ limit }} caracteres." }
        nombre:
            - NotBlank:
                message: El campo Nombre no puede ser vacío.
            - Type: { type: string, message: "El nombre debe ser texto." }
        apellido:
            - NotBlank:
                message: El campo Apellido no puede ser vacío.
            - Type: { type: string, message: "El apellido debe ser texto." }
        imagen:
            - Image:
                maxSize: 5120k
                mimeTypesMessage: Sólo JPG, GIF y PNG, máx. 5 MB.