<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class LoogaresExtraBundleEntityComunaProxy extends \Loogares\ExtraBundle\Entity\Comuna implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setSlug($slug)
    {
        $this->__load();
        return parent::setSlug($slug);
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }

    public function setMapa($mapa)
    {
        $this->__load();
        return parent::setMapa($mapa);
    }

    public function getMapa()
    {
        $this->__load();
        return parent::getMapa();
    }

    public function setHabilitado($habilitado)
    {
        $this->__load();
        return parent::setHabilitado($habilitado);
    }

    public function getHabilitado()
    {
        $this->__load();
        return parent::getHabilitado();
    }

    public function setPais(\Loogares\ExtraBundle\Entity\Ciudad $pais)
    {
        $this->__load();
        return parent::setPais($pais);
    }

    public function getPais()
    {
        $this->__load();
        return parent::getPais();
    }

    public function setMostrarLugar($mostrarLugar)
    {
        $this->__load();
        return parent::setMostrarLugar($mostrarLugar);
    }

    public function getMostrarLugar()
    {
        $this->__load();
        return parent::getMostrarLugar();
    }

    public function setCiudad(\Loogares\ExtraBundle\Entity\Ciudad $ciudad)
    {
        $this->__load();
        return parent::setCiudad($ciudad);
    }

    public function getCiudad()
    {
        $this->__load();
        return parent::getCiudad();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'slug', 'mapa', 'mostrar_lugar', 'ciudad');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}