<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class LoogaresLugarBundleEntityCategoriaProxy extends \Loogares\LugarBundle\Entity\Categoria implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setSlug($slug)
    {
        $this->__load();
        return parent::setSlug($slug);
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }

    public function setMostrarPrecio($mostrarPrecio)
    {
        $this->__load();
        return parent::setMostrarPrecio($mostrarPrecio);
    }

    public function getMostrarPrecio()
    {
        $this->__load();
        return parent::getMostrarPrecio();
    }

    public function setTipoCategoriaId($tipoCategoriaId)
    {
        $this->__load();
        return parent::setTipoCategoriaId($tipoCategoriaId);
    }

    public function getTipoCategoriaId()
    {
        $this->__load();
        return parent::getTipoCategoriaId();
    }

    public function setTipoCategoria(\Loogares\LugarBundle\Entity\TipoCategoria $tipoCategoria)
    {
        $this->__load();
        return parent::setTipoCategoria($tipoCategoria);
    }

    public function getTipoCategoria()
    {
        $this->__load();
        return parent::getTipoCategoria();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'slug', 'mostrar_precio', 'tipo_categoria_id', 'tipo_categoria');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}