<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class LoogaresUsuarioBundleEntityUsuarioProxy extends \Loogares\UsuarioBundle\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setApellido($apellido)
    {
        $this->__load();
        return parent::setApellido($apellido);
    }

    public function getApellido()
    {
        $this->__load();
        return parent::getApellido();
    }

    public function setUsuario($usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setSlug($slug)
    {
        $this->__load();
        return parent::setSlug($slug);
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }

    public function setMail($mail)
    {
        $this->__load();
        return parent::setMail($mail);
    }

    public function getMail()
    {
        $this->__load();
        return parent::getMail();
    }

    public function setTelefono($telefono)
    {
        $this->__load();
        return parent::setTelefono($telefono);
    }

    public function getTelefono()
    {
        $this->__load();
        return parent::getTelefono();
    }

    public function setSexo($sexo)
    {
        $this->__load();
        return parent::setSexo($sexo);
    }

    public function getSexo()
    {
        $this->__load();
        return parent::getSexo();
    }

    public function setLink1($link1)
    {
        $this->__load();
        return parent::setLink1($link1);
    }

    public function getLink1()
    {
        $this->__load();
        return parent::getLink1();
    }

    public function setLink2($link2)
    {
        $this->__load();
        return parent::setLink2($link2);
    }

    public function getLink2()
    {
        $this->__load();
        return parent::getLink2();
    }

    public function setLink3($link3)
    {
        $this->__load();
        return parent::setLink3($link3);
    }

    public function getLink3()
    {
        $this->__load();
        return parent::getLink3();
    }

    public function setImagenFull($imagenFull)
    {
        $this->__load();
        return parent::setImagenFull($imagenFull);
    }

    public function getImagenFull()
    {
        $this->__load();
        return parent::getImagenFull();
    }

    public function setFechaNacimiento($fechaNacimiento)
    {
        $this->__load();
        return parent::setFechaNacimiento($fechaNacimiento);
    }

    public function getFechaNacimiento()
    {
        $this->__load();
        return parent::getFechaNacimiento();
    }

    public function setFechaRegistro($fechaRegistro)
    {
        $this->__load();
        return parent::setFechaRegistro($fechaRegistro);
    }

    public function getFechaRegistro()
    {
        $this->__load();
        return parent::getFechaRegistro();
    }

    public function setFechaUltimaActividad($fechaUltimaActividad)
    {
        $this->__load();
        return parent::setFechaUltimaActividad($fechaUltimaActividad);
    }

    public function getFechaUltimaActividad()
    {
        $this->__load();
        return parent::getFechaUltimaActividad();
    }

    public function setConfirmado($confirmado)
    {
        $this->__load();
        return parent::setConfirmado($confirmado);
    }

    public function getConfirmado()
    {
        $this->__load();
        return parent::getConfirmado();
    }

    public function setNewsletterActivo($newsletterActivo)
    {
        $this->__load();
        return parent::setNewsletterActivo($newsletterActivo);
    }

    public function getNewsletterActivo()
    {
        $this->__load();
        return parent::getNewsletterActivo();
    }

    public function setHashConfirmacion($hashConfirmacion)
    {
        $this->__load();
        return parent::setHashConfirmacion($hashConfirmacion);
    }

    public function getHashConfirmacion()
    {
        $this->__load();
        return parent::getHashConfirmacion();
    }

    public function setCookie($cookie)
    {
        $this->__load();
        return parent::setCookie($cookie);
    }

    public function getCookie()
    {
        $this->__load();
        return parent::getCookie();
    }

    public function setFacebookUid($facebookUid)
    {
        $this->__load();
        return parent::setFacebookUid($facebookUid);
    }

    public function getFacebookUid()
    {
        $this->__load();
        return parent::getFacebookUid();
    }

    public function setFacebookNoPublicar($facebookNoPublicar)
    {
        $this->__load();
        return parent::setFacebookNoPublicar($facebookNoPublicar);
    }

    public function getFacebookNoPublicar()
    {
        $this->__load();
        return parent::getFacebookNoPublicar();
    }

    public function setFacebookData($facebookData)
    {
        $this->__load();
        return parent::setFacebookData($facebookData);
    }

    public function getFacebookData()
    {
        $this->__load();
        return parent::getFacebookData();
    }

    public function setFechaFacebookUltimaActividad($fechaFacebookUltimaActividad)
    {
        $this->__load();
        return parent::setFechaFacebookUltimaActividad($fechaFacebookUltimaActividad);
    }

    public function getFechaFacebookUltimaActividad()
    {
        $this->__load();
        return parent::getFechaFacebookUltimaActividad();
    }

    public function setComuna(\Loogares\ExtraBundle\Entity\Comuna $comuna)
    {
        $this->__load();
        return parent::setComuna($comuna);
    }

    public function getComuna()
    {
        $this->__load();
        return parent::getComuna();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'apellido', 'usuario', 'password', 'slug', 'mail', 'telefono', 'sexo', 'link1', 'link2', 'link3', 'imagen_full', 'fecha_nacimiento', 'fecha_registro', 'fecha_ultima_actividad', 'confirmado', 'newsletter_activo', 'hash_confirmacion', 'cookie', 'facebook_uid', 'facebook_no_publicar', 'facebook_data', 'fecha_facebook_ultima_actividad', 'comuna');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}