<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class LoogaresLugarBundleEntityLugarProxy extends \Loogares\LugarBundle\Entity\Lugar implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setUsuarioId($usuarioId)
    {
        $this->__load();
        return parent::setUsuarioId($usuarioId);
    }

    public function getUsuarioId()
    {
        $this->__load();
        return parent::getUsuarioId();
    }

    public function setSlug($slug)
    {
        $this->__load();
        return parent::setSlug($slug);
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }

    public function setCalle($calle)
    {
        $this->__load();
        return parent::setCalle($calle);
    }

    public function getCalle()
    {
        $this->__load();
        return parent::getCalle();
    }

    public function setNumero($numero)
    {
        $this->__load();
        return parent::setNumero($numero);
    }

    public function getNumero()
    {
        $this->__load();
        return parent::getNumero();
    }

    public function setDetalle($detalle)
    {
        $this->__load();
        return parent::setDetalle($detalle);
    }

    public function getDetalle()
    {
        $this->__load();
        return parent::getDetalle();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function setDuenoId($duenoId)
    {
        $this->__load();
        return parent::setDuenoId($duenoId);
    }

    public function getDuenoId()
    {
        $this->__load();
        return parent::getDuenoId();
    }

    public function setMapx($mapx)
    {
        $this->__load();
        return parent::setMapx($mapx);
    }

    public function getMapx()
    {
        $this->__load();
        return parent::getMapx();
    }

    public function setMapy($mapy)
    {
        $this->__load();
        return parent::setMapy($mapy);
    }

    public function getMapy()
    {
        $this->__load();
        return parent::getMapy();
    }

    public function setProfesional($profesional)
    {
        $this->__load();
        return parent::setProfesional($profesional);
    }

    public function getProfesional()
    {
        $this->__load();
        return parent::getProfesional();
    }

    public function setAgnoConstruccion($agnoConstruccion)
    {
        $this->__load();
        return parent::setAgnoConstruccion($agnoConstruccion);
    }

    public function getAgnoConstruccion()
    {
        $this->__load();
        return parent::getAgnoConstruccion();
    }

    public function setMateriales($materiales)
    {
        $this->__load();
        return parent::setMateriales($materiales);
    }

    public function getMateriales()
    {
        $this->__load();
        return parent::getMateriales();
    }

    public function setSitioWeb($sitioWeb)
    {
        $this->__load();
        return parent::setSitioWeb($sitioWeb);
    }

    public function getSitioWeb()
    {
        $this->__load();
        return parent::getSitioWeb();
    }

    public function setFacebook($facebook)
    {
        $this->__load();
        return parent::setFacebook($facebook);
    }

    public function getFacebook()
    {
        $this->__load();
        return parent::getFacebook();
    }

    public function setTwitter($twitter)
    {
        $this->__load();
        return parent::setTwitter($twitter);
    }

    public function getTwitter()
    {
        $this->__load();
        return parent::getTwitter();
    }

    public function setMail($mail)
    {
        $this->__load();
        return parent::setMail($mail);
    }

    public function getMail()
    {
        $this->__load();
        return parent::getMail();
    }

    public function setTelefono1($telefono1)
    {
        $this->__load();
        return parent::setTelefono1($telefono1);
    }

    public function getTelefono1()
    {
        $this->__load();
        return parent::getTelefono1();
    }

    public function setTelefono2($telefono2)
    {
        $this->__load();
        return parent::setTelefono2($telefono2);
    }

    public function getTelefono2()
    {
        $this->__load();
        return parent::getTelefono2();
    }

    public function setTelefono3($telefono3)
    {
        $this->__load();
        return parent::setTelefono3($telefono3);
    }

    public function getTelefono3()
    {
        $this->__load();
        return parent::getTelefono3();
    }

    public function setEstrellas($estrellas)
    {
        $this->__load();
        return parent::setEstrellas($estrellas);
    }

    public function getEstrellas()
    {
        $this->__load();
        return parent::getEstrellas();
    }

    public function setVisitas($visitas)
    {
        $this->__load();
        return parent::setVisitas($visitas);
    }

    public function getVisitas()
    {
        $this->__load();
        return parent::getVisitas();
    }

    public function setUtiles($utiles)
    {
        $this->__load();
        return parent::setUtiles($utiles);
    }

    public function getUtiles()
    {
        $this->__load();
        return parent::getUtiles();
    }

    public function setFechaAgregado($fechaAgregado)
    {
        $this->__load();
        return parent::setFechaAgregado($fechaAgregado);
    }

    public function getFechaAgregado()
    {
        $this->__load();
        return parent::getFechaAgregado();
    }

    public function setFechaUltimaRecomendacion($fechaUltimaRecomendacion)
    {
        $this->__load();
        return parent::setFechaUltimaRecomendacion($fechaUltimaRecomendacion);
    }

    public function getFechaUltimaRecomendacion()
    {
        $this->__load();
        return parent::getFechaUltimaRecomendacion();
    }

    public function setTotalRecomendaciones($totalRecomendaciones)
    {
        $this->__load();
        return parent::setTotalRecomendaciones($totalRecomendaciones);
    }

    public function getTotalRecomendaciones()
    {
        $this->__load();
        return parent::getTotalRecomendaciones();
    }

    public function setPrecio($precio)
    {
        $this->__load();
        return parent::setPrecio($precio);
    }

    public function getPrecio()
    {
        $this->__load();
        return parent::getPrecio();
    }

    public function setPrecioInicial($precioInicial)
    {
        $this->__load();
        return parent::setPrecioInicial($precioInicial);
    }

    public function getPrecioInicial()
    {
        $this->__load();
        return parent::getPrecioInicial();
    }

    public function setPrioridadWeb($prioridadWeb)
    {
        $this->__load();
        return parent::setPrioridadWeb($prioridadWeb);
    }

    public function getPrioridadWeb()
    {
        $this->__load();
        return parent::getPrioridadWeb();
    }

    public function setComuna(\Loogares\ExtraBundle\Entity\Comuna $comuna)
    {
        $this->__load();
        return parent::setComuna($comuna);
    }

    public function getComuna()
    {
        $this->__load();
        return parent::getComuna();
    }

    public function setSector(\Loogares\ExtraBundle\Entity\Sector $sector)
    {
        $this->__load();
        return parent::setSector($sector);
    }

    public function getSector()
    {
        $this->__load();
        return parent::getSector();
    }

    public function setTipoLugar(\Loogares\LugarBundle\Entity\TipoLugar $tipoLugar)
    {
        $this->__load();
        return parent::setTipoLugar($tipoLugar);
    }

    public function getTipoLugar()
    {
        $this->__load();
        return parent::getTipoLugar();
    }

    public function setEstado(\Loogares\ExtraBundle\Entity\Estado $estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'usuario_id', 'slug', 'calle', 'numero', 'detalle', 'descripcion', 'dueno_id', 'mapx', 'mapy', 'profesional', 'agno_construccion', 'materiales', 'sitio_web', 'facebook', 'twitter', 'mail', 'telefono1', 'telefono2', 'telefono3', 'estrellas', 'visitas', 'utiles', 'fecha_agregado', 'fecha_ultima_recomendacion', 'total_recomendaciones', 'precio', 'precio_inicial', 'prioridad_web', 'comuna', 'sector', 'tipo_lugar', 'estado');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}