Loogares\LugarBundle\Entity\Caracteristica:
    type: entity
    table: caracteristica
    gedmo:
        translation:
            locale: locale
    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        nombre:
            type: string
            gedmo:
                - translatable
        texto:
            type: string
            gedmo:
                - translatable
        slug:
            type: string
            gedmo:
                - translatable
        color:
            type: string
        orden:
            type: string
    indexes:
        idx_caracteristica_slug:
            columns: ["slug"]