Loogares\LugarBundle\Entity\CaracteristicaLugar:
    type: entity
    table: caracteristica_lugar
    manyToOne:
        caracteristica:
            targetEntity: Loogares\LugarBundle\Entity\Caracteristica
            joinTable:
                name: caracteristica_lugar
                joinColumns:
                    caracteristica:
                        referencedColumnName: id
        lugar:
            targetEntity: Loogares\LugarBundle\Entity\Lugar
            joinTable:
                name: caracteristica_lugar
                joinColumns:
                    lugar:
                        referencedColumnName: id
    id:
        id:
            type: integer
            generator: { strategy: auto }