Loogares\LugarBundle\Entity\Categoria:
    type: entity
    table: categorias
    gedmo:
        translation:
            locale: locale
    manyToOne:
        tipo_categoria:
            targetEntity: Loogares\LugarBundle\Entity\TipoCategoria
    oneToMany:
        categoria_lugar:
            targetEntity: Loogares\LugarBundle\Entity\CategoriaLugar
            mappedBy: categoria
        subcategorias:
            targetEntity: Loogares\LugarBundle\Entity\SubCategoria
            mappedBy: categoria

    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        nombre:
            type: string
            gedmo:
                - translatable
        slug:
            type: string
            gedmo:
                - translatable
        mostrar_precio:
            type: smallint
        mostrar_categoria:
            type: smallint