Loogares\LugarBundle\Entity\Horario:
    type: entity
    table: horario
    manyToOne:
        lugar:
            targetEntity: Loogares\LugarBundle\Entity\Lugar
            joinTable:
                name: lugar
                joinColumns:
                    lugar:
                        referencedColumnName: id
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        dia:
            type: smallint
        apertura_am:
            type: string
        cierre_am:
            type: string
        apertura_pm:
            type: string
            nullable: true
        cierre_pm:
            type: string
            nullable: true