Loogares\LugarBundle\Entity\Imagen:
    type: entity
    table: imagenes
    manyToOne:
        caracteristica:
            targetEntity: Loogares\UsuarioBundle\Entity\Usuario
            joinTable:
                name: imagen
                joinColumns:
                    caracteristica:
                        referencedColumnName: id
        lugar:
            targetEntity: Loogares\LugarBundle\Entity\Lugar
            joinTable:
                name: imagen
                joinColumns:
                    lugar:
                        referencedColumnName: id
        estado_imagen:
            targetEntity: Loogares\LugarBundle\Entity\EstadoImagen
            joinTable:
                name: imagen
                joinColumns:
                    estado_imagen:
                        referencedColumnName: id
    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        titulo:
            type: string
        enlace:
            type: integer
        fecha_creacion:
            type: datetime
        fecha_modificacion:
            type: datetime
        imagen_full:
            type: string