Loogares\LugarBundle\Entity\ImagenLugar:
    type: entity
    table: imagenes_lugar
    manyToOne:
        usuario:
            targetEntity: Loogares\UsuarioBundle\Entity\Usuario
            joinTable:
                name: imagen
                joinColumns:
                    usuario:
                        referencedColumnName: id
        lugar:
            targetEntity: Loogares\LugarBundle\Entity\Lugar
            joinTable:
                name: imagen
                joinColumns:
                    lugar:
                        referencedColumnName: id
        estado:
            targetEntity: Loogares\ExtraBundle\Entity\Estado
            joinTable:
                name: imagen
                joinColumns:
                    estado_imagen:
                        referencedColumnName: id
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        es_enlace:
            type: integer
            nullable: true
        titulo_enlace:
            type: string
            nullable: true
        fecha_creacion:
            type: datetime
        fecha_modificacion:
            type: datetime
            nullable: true
        imagen_full:
            type: string

    lifecycleCallbacks:
        preUpdate: [ preUpload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]