Loogares\LugarBundle\Entity\Lugar:
    type: entity
    repositoryClass: Loogares\LugarBundle\Repository\LugarRepository
    table: lugares
    manyToOne:
        comuna:
            targetEntity: Loogares\ExtraBundle\Entity\Comuna
            joinTable:
                name: lugares
                joinColumns:
                    comuna:
                        referencedColumnName: id
        sector:
            targetEntity: Loogares\ExtraBundle\Entity\Sector
            joinTable:
                name: lugares
                joinColumns:
                    sector:
                        referencedColumnName: id
        tipo_lugar:
            targetEntity: Loogares\LugarBundle\Entity\TipoLugar
            joinTable:
                name: lugares
                joinColumns:
                    tipo_lugar:
                        referencedColumnName: id
        estado:
            targetEntity: Loogares\ExtraBundle\Entity\Estado
            joinTable:
                name: lugares
                joinColumns:
                    estado:
                        referencedColumnName: id
    manyToMany:
        imagenes_lugar:
            targetEntity: Loogares\LugarBundle\Entity\ImagenLugar
            mappedBy: lugares
    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        #nombre
        nombre:
            type: string
            length: 50
        #slug
        usuario_id:
            type: integer
        slug:
            type: string
            length: 100
        #direccion
        calle:
            type: string
            length: 255
        numero:
            type: string
            length: 10
        #detalle
        detalle:
            type: text
        #descripcion
        descripcion:
            type: text
        #∫tiene dueno
        dueno_id:
            type: integer
        #mapx
        mapx: 
            type: float
        #mapy
        mapy:
            type: float
        #profesional
        profesional:
            type: string
            length: 50
        #agno construccion
        agno_construccion:
            type: string
            length: 50
        #materiales
        materiales: 
            type: string
            length: 255
        #sitio web
        sitio_web:
            type: string
            length: 100 
        #facebook
        facebook:
            type: string
            length: 100
        #twitter
        twitter: 
            type: string
            length: 100
        #mail
        mail: 
            type: string
            length: 100
        telefono1:
            type: string
        telefono2:
            type: string
        telefono3:
            type: string
        #puntuacion
        estrellas:
            type: float
        #vistas
        visitas:
            type: integer
        #evaluacion
        utiles:
            type: integer
        #fecha
        fecha_agregado:
            type: date
        #fechaultimarecomendacion
        fecha_ultima_recomendacion:
            type: datetime
        #numerorecomendationes
        total_recomendaciones:
            type: integer
        #precio
        precio:
            type: integer
        #precioinicial
        precio_inicial:
            type: integer
        #orden sector
        prioridad_web:
            type: integer