Loogares\LugarBundle\Entity\LugaresEspeciales:
    type: entity
    table: lugares_especiales
    manyToOne:
        lugar:
            targetEntity: Loogares\LugarBundle\Entity\Lugar
            joinTable:
                name: pedido_lugar
                joinColumns:
                    lugar:
                        referencedColumnName: id
    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        link:
            type: integer