Loogares\LugarBundle\Entity\PedidoLugar:
    type: entity
    table: pedidos_lugar
    manyToOne:       
        lugar:
            targetEntity: Loogares\LugarBundle\Entity\Lugar
        servicio_pedido:
            targetEntity: Loogares\LugarBundle\Entity\ServicioPedido
        tipo_pedido:
            targetEntity: Loogares\LugarBundle\Entity\TipoPedido
    oneToOne:
        promocion:
            targetEntity: Loogares\LugarBundle\Entity\Promocion
            mappedBy: pedido_lugar
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        prioridad:
            type: integer
        referral:
            type: text
        tiene_promocion:
            type: boolean