Loogares\LugarBundle\Entity\ReportarLugar:
    type: entity
    table: reportar_lugar
    manyToOne:
        lugar:
            targetEntity: Loogares\LugarBundle\Entity\Lugar
            joinTable:
                name: lugares
                joinColumns:
                    lugar:
                        referencedColumnName: id
        usuario:
            targetEntity: Loogares\UsuarioBundle\Entity\Usuario
            joinTable:
                name: lugares
                joinColumns:
                    usuario:
                        referencedColumnName: id
    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        reporte:
            type: text
        fecha:
            type: datetime