Loogares\LugarBundle\Entity\ReportarRecomendacion:
    type: entity
    table: reportar_recomendacion
    manyToOne:
        recomendacion:
            targetEntity: Loogares\UsuarioBundle\Entity\Recomendacion
        estado:
            targetEntity: Loogares\ExtraBundle\Entity\Estado
        usuario:
            targetEntity: Loogares\UsuarioBundle\Entity\Usuario
            joinTable:
                name: reportar_recomendacion
                joinColumns:
                    sector:
                        referencedColumnName: id
                        nullable: true
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        reporte:
            type: text
        fecha:
            type: datetime
        mail_contacto:
            type: string