Loogares\LugarBundle\Entity\ReportarImagen:
    type: entity
    table: reportar_imagen
    manyToOne:
        imagen_lugar:
            targetEntity: Loogares\LugarBundle\Entity\ImagenLugar
        usuario:
            targetEntity: Loogares\UsuarioBundle\Entity\Usuario
        estado:
            targetEntity: Loogares\ExtraBundle\Entity\Estado
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        reporte:
            type: text
        fecha:
            type: datetime