Loogares\LugarBundle\Entity\ReportarRecomendacion:
    type: entity
    table: reportar_recomendacion
    manyToOne:
        recomendacion:
            targetEntity: Loogares\UsuarioBundle\Entity\Recomendacion
        estado:
            targetEntity: Loogares\ExtraBundle\Entity\Estado
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        reporte:
            type: text
        fecha:
            type: datetime
        mail_contacto:
            type: string