Loogares\LugarBundle\Entity\ReportarRecomendacion:
    type: entity
    table: reportar_recomendacion
    manyToOne:
        recomendacion:
            targetEntity: Loogares\UsuarioBundle\Entity\Recomendacion
            joinTable:
                name: lugares
                joinColumns:
                    recomendacion:
                        referencedColumnName: id
        usuario:
            targetEntity: Loogares\UsuarioBundle\Entity\Usuario
            joinTable:
                name: lugares
                joinColumns:
                    usuario:
                        referencedColumnName: id
    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        reporte:
            type: text
        fecha:
            type: datetime