Loogares\LugarBundle\Entity\ReportarLugar:
    type: entity
    table: reportar_lugar
    manyToOne:
        lugar:
            targetEntity: Loogares\LugarBundle\Entity\Lugar
        estado:
            targetEntity: Loogares\ExtraBundle\Entity\Estado
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        reporte:
            type: text
        fecha:
            type: datetime
        mail_contacto:
            type: string