Loogares\LugarBundle\Entity\SubCategoria:
    type: entity
    table: subcategoria
    gedmo:
        translation:
            locale: locale
    manyToOne:
        categoria:
            targetEntity: Loogares\LugarBundle\Entity\Categoria
    oneToMany:
        subcategoria_lugar:
            targetEntity: Loogares\LugarBundle\Entity\SubcategoriaLugar
            mappedBy: subcategoria
    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        nombre:
            type: string
            gedmo:
                - translatable
        slug:
            type: string
            gedmo:
                - translatable
    indexes:
        idx_subcategoria_slug:
            columns: ["slug"]