Loogares\LugarBundle\Entity\SubCategoria:
    type: entity
    table: subcategoria
    manyToOne:
        categoria:
            targetEntity: Loogares\LugarBundle\Entity\Categoria
    oneToMany:
        subcategoria_lugar:
            targetEntity: Loogares\LugarBundle\Entity\SubcategoriaLugar
            mappedBy: subcategoria
    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        nombre:
            type: string
        slug:
            type: string