Loogares\LugarBundle\Entity\SubcategoriaLugar:
    type: entity
    table: subcategoria_lugar
    manyToOne:
        subcategoria:
            targetEntity: Loogares\LugarBundle\Entity\SubCategoria
            joinTable:
                name: categoria_lugar
                joinColumns:
                    subcategoria:
                        referencedColumnName: id
        lugar:
            targetEntity: Loogares\LugarBundle\Entity\Lugar
            joinTable:
                name: categoria_lugar
                joinColumns:
                    lugar:
                        referencedColumnName: id
    id:
        id:
            type: integer
            generator: { strategy: auto }