Loogares\LugarBundle\Entity\TipoCategoria:
    type: entity
    table: tipo_categoria
    gedmo:
        translation:
            locale: locale
    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        nombre:
            type: string
            gedmo:
                - translatable
        slug:
            type: string
            gedmo:
                - translatable
        prioridad_web:
            type: string