Loogares\LugarBundle\Entity\TipoLugar:
    type: entity
    table: tipo_lugar
    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        nombre:
            type: string
            gedmo:
                - translatable
        slug:
            type: string
            gedmo:
                - translatable
        prioridad_web:
            type: smallint
    indexes:
        idx_tipo_lugar_slug:
            columns: ["slug"]