imports:
    - { resource: parameters.ini }
    - { resource: apis.ini }
    - { resource: security.yml }
    hello_bundle:
        resource: @LoogaresExtraBundle/Resources/config/services.yml 

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:    
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        googlemaps_apikey: %googlemaps_apikey%
        adsense_service: %adsense_service%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        yui_css:
             jar: %kernel.root_dir%/java/yuicompressor-2.4.7.ja

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:        
        auto_generate_proxy_classes: %kernel.debug%
        #auto_mapping: true
        default_entity_manager:   default
        entity_managers:
            default:
                connection: default
                mappings:
                    LoogaresAdminBundle: ~
                    LoogaresExtraBundle: ~
                    LoogaresUsuarioBundle: ~
                    LoogaresLugarBundle: ~
                    LoogaresBlogBundle: ~
                    StofDoctrineExtensionsBundle: ~
                dql:
                    string_functions:
                        RAND: Loogares\ExtraBundle\DQL\Rand


# Swiftmailer Configuratn
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# Avalanche Imagine Configuration
avalanche_imagine:
    web_root:     %kernel.root_dir%/../web
    cache_prefix: assets/media/cache
    driver:       gd
    filters:
        tiny_usuario:
            type:    thumbnail
            options: { size: [20, 20], mode: outbound }
        small_usuario:
            type:    thumbnail
            options: { size: [60, 60], mode: outbound }
        medium_usuario:
            type:    thumbnail
            options: { size: [140, 140], mode: outbound }
        tiny_lugar:
            type:    thumbnail
            options: { size: [36, 36], mode: outbound }
        small_lugar:
            type:    thumbnail
            options: { size: [50, 50], mode: outbound }
        medium_lugar:
            type:    thumbnail
            options: { size: [130, 130], mode: outbound }
        large_lugar:
            type:    thumbnail
            options: { size: [600, 500], mode: outbound }
        blog:
            type:    thumbnail
            options: { size: [600, 300], mode: outbound }
        blog_detalle:
            type:    thumbnail
            options: { size: [145, 145], mode: outbound }

# MailChimp Configuration
jirafe_mail_chimp:
    api_key:    %mailchimp_apikey%
    connection: stub

# Doctrine Extensions Configuration
stof_doctrine_extensions:
    default_locale: es_AR
    translation_fallback: true
    orm:
        default:
            translatable: true

# FOS Facebook Configuration
fos_facebook:
    file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
    alias:  facebook
    app_id: %facebook_appid%
    secret: %facebook_appsecret%
    cookie: true
    permissions: [email, user_birthday, user_location, user_photos]
    culture: es_LA
