_imagine:
    resource: .
    type:     imagine

LoogaresUsuarioBundle:
    resource: "@LoogaresUsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

LoogaresLugarBundle:
    resource: "@LoogaresLugarBundle/Resources/config/routing.yml"
    prefix:   /

LoogaresAdminBundle:
    resource: "@LoogaresAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

LoogaresExtraBundle:
    resource: "@LoogaresExtraBundle/Resources/config/routing.yml"
    prefix:   /
    
root:
    pattern:   /
    defaults:  { _controller: LoogaresExtraBundle:Default:homepage }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
