LoogaresCampanaBundle:
    resource: "@LoogaresCampanaBundle/Resources/config/routing.yml"
    prefix:   /

LoogaresPhoneBundle:
    resource: "@LoogaresPhoneBundle/Resources/config/routing.yml"
    prefix:   /

LoogaresMailBundle:
    resource: "@LoogaresMailBundle/Resources/config/routing.yml"
    prefix:   /

LoogaresBlogBundle:
    resource: "@LoogaresBlogBundle/Resources/config/routing.yml"
    prefix:   /

_imagine:
    resource: .
    type:     imagine

LoogaresUsuarioBundle:
    resource: "@LoogaresUsuarioBundle/Resources/config/routing.yml"
    prefix: /
    type: be_simple_i18n

LoogaresLugarBundle:
    resource: "@LoogaresLugarBundle/Resources/config/routing.yml"
    prefix:   /
    type: be_simple_i18n

LoogaresAdminBundle:
    resource: "@LoogaresAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

LoogaresExtraBundle:
    resource: "@LoogaresExtraBundle/Resources/config/routing.yml"
    prefix:   /

root:
    pattern:   /
    defaults:  { _controller: LoogaresExtraBundle:Default:homepage }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
