LoogaresExtraBundle:
    resource: "@LoogaresExtraBundle/Resources/config/routing.yml"
    prefix:   /

LoogaresUsuarioBundle:
    resource: "@LoogaresUsuarioBundle/Resources/config/routing.yml"
    prefix:   /

LoogaresLugarBundle:
    resource: "@LoogaresLugarBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
