LoogaresExtraBundle:
    resource: "@LoogaresExtraBundle/Resources/config/routing.yml"
    prefix:   /

LoogaresUsuarioBundle:
    resource: "@LoogaresUsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuarios

LoogaresLugarBundle:
    resource: "@LoogaresLugarBundle/Resources/config/routing.yml"
    prefix:   /

LoogaresAdminBundle:
    resource: "@LoogaresAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

#_security_check:
#    pattern:  /login_check
#_security_logout:
#    pattern:  /logout

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
