security:
    factories:
        - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"
    encoders: 
        Loogares\UsuarioBundle\Entity\Usuario:
            id: sha1_login_encoder

    role_hierarchy:
        ROLE_ADMIN:        ROLE_USER
        ROLE_COLLABORATOR: ROLE_USER

    providers:
        chain_provider:
            providers: [main, facebook]
        main:           
            entity: { class: Loogares\UsuarioBundle\Entity\Usuario }
        facebook:
            id: my.facebook.user

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~            
            form_login:
                check_path: /usuario/login_check
                login_path: /usuario
                username_parameter: _mail
                default_target_path: /usuario
                provider: main
            fos_facebook:
                app_url: "http://new.loogares.com"
                server_url: "http://new.loogares.com"
                check_path: /usuario/login_check_facebook
                login_path: /usuario
                default_target_path: /usuario
                provider: facebook
            logout:
                path:   /usuario/logout
                target: /
            remember_me:
                key: remember
                lifetime: 1209600
                path:     /
                domain:   ~         
    access_control:
        - { path: /agregar, roles: ROLE_USER }
        - { path: /editar, roles: ROLE_USER }
        - { path: /reportar, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }

    acl:
        connection: default