security:
    factories:
        - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"
    encoders:        
        Loogares\UsuarioBundle\Entity\Usuario:
            algorithm: md5
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:           
            entity: { class: Loogares\UsuarioBundle\Entity\Usuario }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            provider: main
            form_login:
                check_path: /usuario/login_check
                login_path: /usuario
                username_parameter: _mail
                default_target_path: /usuario
            logout:
                path:   /usuario/logout
                target: /usuario
            remember_me:
                key: remember
                lifetime: 1209600
            fos_facebook:
                app_url: "http://new.loogares.com"
                server_url: "http://new.loogares.com" 
    access_control:
        - { path: /agregar, roles: ROLE_USER }
        - { path: /editar, roles: ROLE_USER }
        - { path: /reportar, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }

    acl:
        connection: default