security:
    encoders:        
        Loogares\UsuarioBundle\Entity\Usuario:
            algorithm: md5
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:           
            entity: { class: Loogares\UsuarioBundle\Entity\Usuario }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            provider: main
            form_login:
                check_path: /usuarios/login_check
                login_path: /usuarios
                username_parameter: _mail
            logout:
                path:   /usuarios/logout
                target: /
            remember_me:
                key: remember
#            fos_facebook:
 #               app_url: "http://apps.facebook.com/Loogares.com/"
  #              server_url: "http://localhost/loogares/app_dev.php/" 
    access_control:
        - { path: ^/lugar/agregar, roles: ROLE_USER }
        - { path: /editar, roles: ROLE_USER }

    acl:
        connection: default