Loogares\BlogBundle\Entity\Categoria:
    type: entity
    table: blog_categoria
    manyToOne:       
        blog_tipo_post:
            targetEntity: Loogares\BlogBundle\Entity\TipoPost
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:      
        nombre:
            type: string
        slug:
            type: string
        hex:
            type: string
            nullable: true
        clase:
            type: string
            nullable: true