Loogares\BlogBundle\Entity\Concurso:
    type: entity
    repositoryClass: Loogares\BlogBundle\Repository\ConcursoRepository
    table: concursos
    manyToOne:
        post:
            targetEntity: Loogares\BlogBundle\Entity\Posts
        estado_concurso:
            targetEntity: Loogares\BlogBundle\Entity\EstadoConcurso
        tipo_concurso:
            targetEntity: Loogares\BlogBundle\Entity\TipoConcurso

    oneToMany:
        participantes:
            targetEntity: Loogares\BlogBundle\Entity\Participante
            mappedBy: concurso
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        titulo:
            type: string
        descripcion:
            type: string
            nullable: true
        numero_premios:
            type: integer
            nullable: true
        fecha_inicio:
            type: datetime
        fecha_termino:
            type: datetime
        twitter_inicio:
            type: integer
            nullable: true
        twitter_final:
            type: integer
            nullable: true
        facebook_inicio:
            type: integer
            nullable: true
        facebook_final:
            type: integer
            nullable: true
        visitas_home:
            type: integer
            nullable: true
        visitas_busquedas:
            type: integer
            nullable: true
        visitas_categorias:
            type: integer
            nullable: true
        visitas_post:
            type: integer
            nullable: true
        visitas_ficha:
            type: integer
            nullable: true