Loogares\BlogBundle\Entity\EstadoConcurso:
    type: entity
    table: estado_concurso
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        nombre:
            type: string
        slug:
            type: string
        clase:
            type: string
            nullable: true
    indexes:
        idx_estado_concurso_slug:
            columns: ["slug"]