Loogares\BlogBundle\Entity\Participante:
    type: entity
    table: participantes
    manyToOne:       
        concurso:
            targetEntity: Loogares\BlogBundle\Entity\Concurso
        usuario:
            targetEntity: Loogares\UsuarioBundle\Entity\Usuario
    oneToOne:
        ganador:
            targetEntity: Loogares\BlogBundle\Entity\Ganador
            mappedBy: participante
    id:
        id:
            type: integer
            generator: { strategy: auto }