Loogares\BlogBundle\Entity\Posts:
    type: entity
    table: blog_posts
    manyToOne:       
        lugar:
            targetEntity: Loogares\LugarBundle\Entity\Lugar
        ciudad:
            targetEntity: Loogares\ExtraBundle\Entity\Ciudad
        usuario:
            targetEntity: Loogares\UsuarioBundle\Entity\Usuario
        blog_categoria:
            targetEntity: Loogares\BlogBundle\Entity\Categoria
        blog_estado_concurso:
            targetEntity: Loogares\BlogBundle\Entity\EstadoConcurso
        blog_estado:
            targetEntity: Loogares\BlogBundle\Entity\Estado
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:      
        titulo:
            type: string
        slug:
            type: string
        titulo_home:
            type: string
        descripcion_home:
            type: string
        imagen:
            type: string
        imagen_detalle:
            type: string
        imagen_home:
            type: string
        contenido:
            type: text
        preview:
            type: string
        fecha:
            type: date
        fecha_publicacion:
            type: datetime
            nullable: true
        fecha_termino:
            type: datetime
            nullable: true
        condiciones:
            type: text
        numero_premios:
            type: smallint
        ganadores:
            type: text
        detalles:
            type: text
        destacado_home:
            type: smallint
        posicion_home:
            type: smallint
