Loogares\BlogBundle\Entity\Posts:
    type: entity
    table: posts
    manyToOne:       
        lugar:
            targetEntity: Loogares\LugarBundle\Entity\Lugar
        usuario:
            targetEntity: Loogares\UsuarioBundle\Entity\Usuario
        ciudad:
            targetEntity: Loogares\ExtraBundle\Entity\Ciudad
        tipo_post:
            targetEntity: Loogares\BlogBundle\Entity\TipoPost
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:      
        titulo:
            type: string
        slug:
            type: string
        titulo_home:
            type: string
        descripcion_home:
            type: string
        imagen:
            type: string
        imagen_detalle:
            type: string
        imagen_home:
            type: string
        contenido:
            type: text
        preview:
            type: string
        fecha:
            type: date
        fecha_publicacion:
            type: datetime
        fecha_termino:
            type: datetime
            nullable: true
        condiciones:
            type: text
        numero_premios:
            type: smallint
        ganadores:
            type: text
        detalles:
            type: text
        publicado:
            type: smallint
        titulo_alianza_estado:
            type: string
        destacado_home:
            type: smallint
