Loogares\BlogBundle\Entity\Posts:
    type: entity
    repositoryClass: Loogares\BlogBundle\Repository\PostRepository
    table: blog_posts
    manyToOne:       
        lugar:
            targetEntity: Loogares\LugarBundle\Entity\Lugar
        ciudad:
            targetEntity: Loogares\ExtraBundle\Entity\Ciudad
        usuario:
            targetEntity: Loogares\UsuarioBundle\Entity\Usuario
        blog_categoria:
            targetEntity: Loogares\BlogBundle\Entity\Categoria
        blog_estado_concurso:
            targetEntity: Loogares\BlogBundle\Entity\EstadoConcurso
        blog_estado:
            targetEntity: Loogares\BlogBundle\Entity\Estado
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:      
        titulo:
            type: string
        slug:
            type: string
        titulo_home:
            type: string
            nullable: true
        descripcion_home:
            type: string
            nullable: true
        imagen:
            type: string
            nullable: true
        imagen_detalle:
            type: string
            nullable: true
        imagen_home:
            type: string
            nullable: true
        contenido:
            type: text
        preview:
            type: text
        fecha:
            type: date
        fecha_publicacion:
            type: datetime
            nullable: true
        fecha_termino:
            type: datetime
            nullable: true
        condiciones:
            type: text
            nullable: true
        numero_premios:
            type: smallint
            nullable: true
        ganadores:
            type: text
            nullable: true
        detalles:
            type: text
            nullable: true
        destacado_home:
            type: smallint
        posicion_home:
            type: smallint

    lifecycleCallbacks:
        prePersist: [ preUpload ]
        postPersist: [ upload ]
        preUpdate: [ preUploadUpdate ]
        postUpdate: [ uploadUpdate ]
        postRemove: [ removeUpload ]
