Loogares\BlogBundle\Entity\TipoPost:
    type: entity
    table: blog_tipo_post
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        nombre:
            type: string
        slug:
            type: string
        hex:
            type: string
        clase:
            type: string
    indexes:
        idx_blog_tipo_post_slug:
            columns: ["slug"]