Loogares\BlogBundle\Entity\TipoConcurso:
    type: entity
    table: tipo_concurso
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        nombre:
            type: string
        slug:
            type: string
    indexes:
        idx_tipo_concurso_slug:
            columns: ["slug"]