<?php

namespace Loogares\ExtraBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActividadRecienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadRecienteRepository extends EntityRepository
{
	public function getActividadReciente($results, $ciudad=null, $usuario=null, $entity=null, $offset=null) {
		$em = $this->getEntityManager();

		if($offset == null)
          	$offset = '';
        if($ciudad != null)
        	$where = ' WHERE ar.ciudad = '.$ciudad;
        if($usuario != null)
        	$where = ' WHERE ar.usuario = '.$usuario;
        if($entity != null)
        	$where .= ' AND ar.entity = '.$entity;        	

        $q = $em->createQuery("SELECT ar, u
                               FROM Loogares\ExtraBundle\Entity\ActividadReciente ar
                               JOIN ar.usuario u".
                               $where.
                               "ORDER BY ar.fecha DESC")
                ->setMaxResults($results)
                ->setFirstResult($offset);       

        return $q->getResult();
	}
}