<?php

namespace Loogares\ExtraBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CiudadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiudadRepository extends EntityRepository
{
	public function getCiudadesActivas() {
      $em = $this->getEntityManager();
      $q = $em->createQuery("SELECT c 
                             FROM Loogares\ExtraBundle\Entity\Ciudad c 
                             WHERE c.mostrar_lugar = 1 
                             OR c.mostrar_lugar = 3");
      $ciudadesResult = $q->getResult();

      return $ciudadesResult;
    }

  public function getCategoriasPorCiudad($ciudad) {
    	$em = $this->getEntityManager();
    	$q = $em->createQuery("SELECT cc, c
    						   FROM Loogares\ExtraBundle\Entity\CategoriaCiudad cc
    						   JOIN cc.categoria c
    						   WHERE cc.ciudad = ?1
    						   ORDER BY c.nombre ASC");
    	$q->setParameter(1, $ciudad);
    	$cc = $q->getResult();

    	$categorias = array();
    	foreach($cc as $catCiudad) {
    		$categorias[] = $catCiudad->getCategoria();
    	}

    	return $categorias;
  }

  public function findOneBySlugActivo($slug) {
      $em = $this->getEntityManager();
      $q = $em->createQuery("SELECT c 
                             FROM Loogares\ExtraBundle\Entity\Ciudad c 
                             WHERE c.slug = ?1
                             AND (c.mostrar_lugar = 1 
                             OR c.mostrar_lugar = 3)");
      $q->setParameter(1, $slug);
      return $q->getOneOrNullResult();
  }
}