<?php

namespace Loogares\ExtraBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CiudadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiudadRepository extends EntityRepository
{
	public function getCiudadesActivas() {
      $em = $this->getEntityManager();
      $q = $em->createQuery("SELECT c FROM Loogares\ExtraBundle\Entity\Ciudad c WHERE c.mostrar_lugar = 1 or c.mostrar_lugar = 3");
      $ciudadesResult = $q->getResult();

      return $ciudadesResult;
    }
}