<?php

namespace Loogares\ExtraBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TiempoRelativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiempoRelativoRepository extends EntityRepository{
        public function tiempoRelativo($time){
        $em = $this->getEntityManager();
        $time = strtotime($time);
        $now = time();
        //+3600 GTM stuff
        $diff = $now + 3600- $time;

        if($diff < 10){
        	$relative = $this->findOneBySlug("justo-ahora")->getTexto();
        }else if($diff < 60){
        	$diff = round($diff);
        	if($diff == 1){
        		$relative = $this->findOneBySlug("hace-x-segundo")->getTexto();
        	}else{
        		$relative = preg_replace('/{{x}}/', $diff, $this->findOneBySlug("hace-x-segundos")->getTexto());
        	}
        }else if($diff < 3600){
        	$diff = round($diff/60);
        	if($diff == 1){
        		$relative = $this->findOneBySlug("hace-x-minuto")->getTexto();
        	}else{
        		$relative = preg_replace('/{{x}}/', $diff, $this->findOneBySlug("hace-x-minutos")->getTexto());
        	}
        }else if($diff < 3600*24){
        	$diff = round($diff/3600);
        	if($diff == 1){
        		$relative = $this->findOneBySlug("hace-x-hora")->getTexto();
        	}else{
        		$relative = preg_replace('/{{x}}/', $diff, $this->findOneBySlug("hace-x-horas")->getTexto());
        	}
        }else if($diff < 3600*24*2){
        	$diff = round($diff/(3600*24));
        	$relative = preg_replace('/{{x}}/', $diff, $this->findOneBySlug("ayer")->getTexto());
        }else if($diff < 3600*24*6){
        	$diff = round($diff/(3600*24));
        	if($diff == 1){
        		$relative = $this->findOneBySlug("hace-x-dia")->getTexto();
        	}else{
        		$relative = preg_replace('/{{x}}/', $diff, $this->findOneBySlug("hace-x-dias")->getTexto());
        	}
        }else if ($diff < 3600*24*8){
        	$diff = round($diff/(3600*24*7));
        	$relative = preg_replace('/{{x}}/', $diff, $this->findOneBySlug("hace-x-semana")->getTexto());
	}else{
        	$relative = date('d/m/Y', $time);
        }
        return $relative;
    }
}
