Loogares\ExtraBundle\Entity\Ciudad:
    type: entity
    repositoryClass: Loogares\ExtraBundle\Repository\CiudadRepository
    table: ciudad
    manyToOne:
        pais:
            targetEntity: Loogares\ExtraBundle\Entity\Pais
            joinTable:
                name: ciudad
                joinColumns:
                    pais:
                        referencedColumnName: id
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        nombre:
            type: string
        slug:
            type: string
        mapa:
            type: string
        mostrar_lugar:
            type: string