Loogares\ExtraBundle\Entity\Ciudad:
    type: entity
    repositoryClass: Loogares\ExtraBundle\Repository\CiudadRepository
    table: ciudad
    manyToOne:
        pais:
            targetEntity: Loogares\ExtraBundle\Entity\Pais
            joinTable:
                name: ciudad
                joinColumns:
                    pais:
                        referencedColumnName: id
    oneToMany:
        comunas:
            targetEntity: Loogares\ExtraBundle\Entity\Comuna
            mappedBy: ciudad
        sectores:
            targetEntity: Loogares\ExtraBundle\Entity\Sector
            mappedBy: ciudad
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        nombre:
            type: string
        slug:
            type: string
        mapa:
            type: string
        mostrar_lugar:
            type: string
    indexes:
        idx_ciudad_slug:
            columns: ["slug"]