Loogares\ExtraBundle\Entity\Pais:
    type: entity
    table: pais
    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        nombre:
            type: string
        slug:
            type: string
        mapa:
            type: string
        mostrar_usuario:
            type: smallint
        mostrar_lugar:
            type: smallint