Loogares\ExtraBundle\Entity\Pais:
    type: entity
    table: pais
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        nombre:
            type: string
        slug:
            type: string
        mapa:
            type: string
        codigo_area:
            type: string
            length: 5
        locale:
            type: string
        mostrar_lugar:
            type: smallint