Loogares\ExtraBundle\Entity\Premios:
    type: entity
    table: premios
    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        nombre:
            type: string
        cantidad:
            type: string
