Loogares\ExtraBundle\Entity\Sector:
    type: entity
    table: sector
    manyToOne:
        ciudad:
            targetEntity: Loogares\ExtraBundle\Entity\Ciudad
            joinTable:
                name: ciudad
                joinColumns:
                    ciudad:
                        referencedColumnName: id
    id:
        id:
            type: integer
            generator: { strategy: none }
    fields:
        nombre:
            type: string
        slug:
            type: string
        mapa:
            type: string
        prioridad_sector:
            type: integer
        mostrar_lugar:
            type: integer
