<?php

namespace Loogares\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConcursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcursoRepository extends EntityRepository
{
	public function getConcursoPost($post) {
        $em = $this->getEntityManager();

        //Query para obtener el total de recomendaciones del usuario        
        $q = $em->createQuery("SELECT c
                               FROM Loogares\BlogBundle\Entity\Concurso c
                               WHERE c.post = ?1");
        $q->setParameter(1, $post);
        
        return $q->getOneOrNullResult();  
    }
}