<?php

namespace Loogares\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

	public function getPostsDestacados($ciudad, $length = null) {
		$em = $this->getEntityManager();

		$q = $em->createQuery("SELECT p FROM Loogares\BlogBundle\Entity\Posts p
                               WHERE p.ciudad = ?1
                               AND p.destacado_home = ?2
                               AND p.blog_estado = ?3
                               ORDER BY p.id DESC");

		if($length != null) {
			$q->setMaxResults($length);
		}
        $q->setParameter(1, $ciudad);
        $q->setParameter(2, 1);
        $q->setParameter(3, 2);

        return $q->getResult();
	}
}