Loogares\MailBundle\Entity\Notificacion:
    type: entity
    repositoryClass: Loogares\MailBundle\Repository\NotificacionRepository
    table: notificaciones
    manyToOne:
        tipo_notificacion:
            targetEntity: Loogares\MailBundle\Entity\TipoNotificacion
        usuario:
            targetEntity: Loogares\UsuarioBundle\Entity\Usuario
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        activa:
            type: boolean