LoogaresCampanaBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: LoogaresCampanaBundle:Default:index }

# GENERAL
_reportes:
    pattern:  /lugar/{slug}/panel_dueno
    defaults: { _controller: LoogaresCampanaBundle:Default:index }

_reporte_campanas:
    pattern: /lugar/{slug}/panel_dueno/campanas
    defaults: { _controller: LoogaresCampanaBundle:Default:listadoCampanas }

# CONCURSOS
_reporte_concursos_detalles:
    pattern: /lugar/{slug}/panel_dueno/campanas/{id}/concursos/{idConcurso}
    defaults: { _controller: LoogaresCampanaBundle:Default:detalleConcurso }

_reporte_concursos_listado:
    pattern: /lugar/{slug}/panel_dueno/campanas/{id}/concursos
    defaults: { _controller: LoogaresCampanaBundle:Default:listadoConcursos }

# DESCUENTOS
_reporte_descuentos_detalle:
    pattern: /lugar/{slug}/panel_dueno/campanas/{id}/descuentos/detalle
    defaults: { _controller: LoogaresCampanaBundle:Default:detalleDescuentos }

_reporte_descuentos_nuevo:
    pattern: /lugar/{slug}/panel_dueno/campanas/{id}/descuentos/nuevo
    defaults: { _controller: LoogaresCampanaBundle:Default:nuevoDescuento }

# MAILS DESCUENTOS
_reporte_descuentos_mail:
    pattern: /lugar/{slug}/panel_dueno/mail
    defaults: { _controller: LoogaresCampanaBundle:Default:mailDescuentosUsuario }

_reporte_descuentos_enviar:
    pattern: /lugar/{slug}/panel_dueno/campanas/{id}/descuento/enviar
    defaults: { _controller: LoogaresCampanaBundle:Default:submitDescuento }

# SEGUIDORES
_reporte_seguidores:
    pattern: /lugar/{slug}/panel_dueno/seguidores
    defaults: { _controller: LoogaresCampanaBundle:Default:seguidores }
