parameters:
#    loogares_campana.example.class: Loogares\CampanaBundle\Example

services:
#    loogares_campana.example:
#        class: %loogares_campana.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
