actividad:
    pattern:  /actividad
    defaults: { _controller: LoogaresExtraBundle:Default:actividad }

sitemap:
    pattern:  /sitemap.{_format}
    defaults: { _controller: LoogaresExtraBundle:Default:sitemap, _format: xml }
    requirements:
        _format:  xml 

locale:
    pattern:  /{slug}
    defaults: { _controller: LoogaresExtraBundle:Default:homepage }
    requirements:
        slug: santiago-de-chile|buenos-aires|valparaiso-vina-del-mar

locale_santiago_de_chile:
    pattern:  /santiago-de-chile
    defaults: { _controller: LoogaresExtraBundle:Default:homepage, slug : santiago-de-chile }

locale_valparaiso_vina_del_mar:
    pattern:  /valparaiso-vina-del-mar
    defaults: { _controller: LoogaresExtraBundle:Default:homepage, slug : valparaiso-vina-del-mar }

locale_buenos_aires:
    pattern:  /buenos-aires
    defaults: { _controller: LoogaresExtraBundle:Default:homepage, slug : buenos-aires }

update_por_recomendar:
    pattern:  /update_por_recomendar
    defaults: { _controller: LoogaresExtraBundle:Default:updatePorRecomendarUsuario }    

static:
    pattern:  /{static}
    defaults: { _controller: LoogaresExtraBundle:Default:Static }

_contacto_mail:
    pattern:  /mail/enviar_contacto
    defaults: { _controller: LoogaresExtraBundle:Default:ContactoMail}

_publicidad_mail:
    pattern:  /mail/enviar_publicidad
    defaults: { _controller: LoogaresExtraBundle:Default:PublicidadMail}