actividad:
    pattern:  /actividad
    defaults: { _controller: LoogaresExtraBundle:Default:actividad }

locale:
    pattern:  /{slug}
    defaults: { _controller: LoogaresExtraBundle:Default:homepage, slug : santiago-de-chile }
    requirements:
        slug: santiago-de-chile|valparaiso-vina-del-mar|buenos-aires

locale_santiago_de_chile:
    pattern:  /santiago-de-chile
    defaults: { _controller: LoogaresExtraBundle:Default:homepage, slug : santiago-de-chile }

locale_valparaiso_vina_del_mar:
    pattern:  /valparaiso-vina-del-mar
    defaults: { _controller: LoogaresExtraBundle:Default:homepage, slug : valparaiso-vina-del-mar }

locale_buenos_aires:
    pattern:  /buenos-aires
    defaults: { _controller: LoogaresExtraBundle:Default:homepage, slug : buenos-aires }

static:
    pattern:  /{static}
    defaults: { _controller: LoogaresExtraBundle:Default:Static}

_contacto_mail:
    pattern:  /mail/enviar_contacto
    defaults: { _controller: LoogaresExtraBundle:Default:ContactoMail}

_publicidad_mail:
    pattern:  /mail/enviar_publicidad
    defaults: { _controller: LoogaresExtraBundle:Default:PublicidadMail}