actividad:
    pattern:  /actividad
    defaults: { _controller: LoogaresExtraBundle:Default:actividad }

sitemap:
    pattern:  /sitemap.{_format}
    defaults: { _controller: LoogaresExtraBundle:Default:sitemap, _format: xml }
    requirements:
        _format:  xml

locale:
    pattern:  /{slug}
    defaults: { _controller: LoogaresExtraBundle:Default:homepage }

locale_santiago_de_chile:
    pattern:  /santiago-de-chile
    defaults: { _controller: LoogaresExtraBundle:Default:homepage, slug : santiago-de-chile }

locale_valparaiso_vina_del_mar:
    pattern:  /valparaiso-vina-del-mar
    defaults: { _controller: LoogaresExtraBundle:Default:homepage, slug : valparaiso-vina-del-mar }

locale_buenos_aires:
    pattern:  /buenos-aires
    defaults: { _controller: LoogaresExtraBundle:Default:homepage, slug : buenos-aires }

locale_sao_paulo:
    pattern:  /sao-paulo
    defaults: { _controller: LoogaresExtraBundle:Default:homepage, slug : sao-paulo }

concursos:
    pattern:  /{ciudad}/concursos
    defaults: { _controller: LoogaresExtraBundle:Default:concursos }

static:
    pattern:  /{static}
    defaults: { _controller: LoogaresExtraBundle:Default:Static }

_contacto_mail:
    pattern:  /mail/enviar_contacto
    defaults: { _controller: LoogaresExtraBundle:Default:ContactoMail}

_publicidad_mail:
    pattern:  /mail/enviar_publicidad
    defaults: { _controller: LoogaresExtraBundle:Default:PublicidadMail}

_beneficio_exclusivo_mail:
    pattern:  /mail/enviar_beneficio_exclusivo
    defaults: { _controller: LoogaresExtraBundle:Default:beneficioExclusivoMail}

concursos_mail:
    pattern:  /{ciudad}/concursos/mail
    defaults: { _controller: LoogaresExtraBundle:Default:mailConcursos }

iphone_mail:
    pattern:  /iphone_app/mail
    defaults: { _controller: LoogaresExtraBundle:Default:mailIphoneApp }

iphone_mail_ar:
    pattern:  /iphone_app/mail_ar
    defaults: { _controller: LoogaresExtraBundle:Default:mailIphoneAppAr }