parameters:
    loogares_fn.class: Loogares\ExtraBundle\Functions\LoogaresFunctions
    loogares_facebook_provider.class: Loogares\UsuarioBundle\Security\User\FacebookProvider

services:
    fn:
        class: %loogares_fn.class%

    my.facebook.user:
        class: %loogares_facebook_provider.class%
        arguments:
            facebook: "@fos_facebook.api"
            em: "@doctrine.orm.default_entity_manager"
            validator: "@validator"
            container: "@service_container"

    twig.extension.loogares:
        class: Loogares\ExtraBundle\Extension\LoogaresExtension
        tags:
            -  { name: twig.extension }

    controllers.action_listener:
        class: Loogares\ExtraBundle\EventListener\BeforeControllerListener
        arguments: [@service_container, @doctrine.orm.default_entity_manager, @controller_resolver]
        tags:
            -  { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    sha1_login_encoder:
        class: Loogares\ExtraBundle\Encoder\Encoder
        arguments:
            em: "@doctrine.orm.default_entity_manager"

    auth_success_handler:
        class: Loogares\ExtraBundle\Authentication\SuccessHandler
        arguments:
            router: "@router"
            em: "@doctrine.orm.default_entity_manager"