parameters:
    loogares_fn.class: Loogares\ExtraBundle\Functions\LoogaresFunctions

services:
    fn:
        class: %loogares_fn.class%

    twig.extension.loogares:
        class: Loogares\ExtraBundle\Extension\LoogaresExtension
        tags:
            -  { name: twig.extension }
