<?php

namespace Loogares\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TempLugarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempLugarRepository extends EntityRepository
{
}