<?php

namespace Loogares\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TempLugarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempLugarRepository extends EntityRepository
{

    public function getTotalLugaresARevisar(){
        $em = $this->getEntityManager();
        $q = $em->createQuery("SELECT count(distinct u.lugar) FROM Loogares\AdminBundle\Entity\TempLugar u where u.estado = ?1");
        $q->setParameter(1, 1);

        return $q->getSingleScalarResult();
    }

    public function getRevisionesPendientes($id){
        $em = $this->getEntityManager();
        $q = $em->createQuery("SELECT count(distinct u.lugar) FROM Loogares\AdminBundle\Entity\TempLugar u where u.lugar = ?1");
        $q->setParameter(1, $id);
        $revisionesPendientesResult = $q->getSingleScalarResult();

        return $revisionesPendientesResult;
    }
}