<?php

namespace Loogares\UsuarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{

	public function getUserReviews($id) {
		$em = $this->getEntityManager();

		//Query para obtener el total de recomendaciones del usuario
        $q = $em->createQuery("SELECT r
                               FROM Loogares\UsuarioBundle\Entity\Recomendacion r 
                               WHERE r.usuario = ?1");
        $q->setParameter(1, $id);

        return $q->getResult();
	}

	public function getLugaresAgregadosUsuario($id) {
		$em = $this->getEntityManager();

		 //Query para obtener el total de lugares agregados por el usuario
        $q = $em->createQuery("SELECT COUNT(l) total 
                               FROM Loogares\LugarBundle\Entity\Lugar l 
                               WHERE l.usuario_id = ?1");
        $q->setParameter(1, $id);
        return $q->getSingleResult();
	}

	public function getFotosLugaresAgregadasUsuario($id) {
		$em = $this->getEntityManager();

		//Query para obtener el total de fotos de lugares agregadas por el usuario
        $q = $em->createQuery("SELECT COUNT(im) total 
                               FROM Loogares\LugarBundle\Entity\ImagenLugar im 
                               WHERE im.usuario = ?1");
        $q->setParameter(1, $id);
        return $q->getSingleResult();
	}

	public function verificarPrimeroRecomendar($idUsuario, $idLugar) {
		$em = $this->getEntityManager();

		//Verificamos si usuario es el primero en recomendar en el lugar
		$q = $em->createQuery("SELECT r
							   FROM LoogaresUsuarioBundle:Recomendacion r
							   WHERE r.lugar = ?1
							   ORDER BY r.fecha_creacion")->setMaxResults(1);

		$q->setParameter(1,$idLugar);

		if($q->getSingleResult()->getUsuario()->getId() == $idUsuario)
			return true;
		else
			return false;
	}


}