LoogaresLugarBundle_homepage:
    pattern:  /agregar
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregar }

_listado:
    pattern: /listado
    defaults: { _controller: LoogaresLugarBundle:Lugar:listado }


_lugar:
    pattern: /lugar/{slug}
    defaults: { _controller: LoogaresLugarBundle:Lugar:lugar }
    requirements:
        page: pag\d+
