LoogaresLugarBundle_homepage:
    pattern:  /agregar
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregar }

_agregar:
    pattern: /lugar/agregar
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregar }

_lugar:
    pattern: /lugar/{slug}
    defaults: { _controller: LoogaresLugarBundle:Lugar:lugar }

_editar:
    pattern: /lugar/editar/{slug}
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregar }

_otrosLugaresEnElArea:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:otrosLugaresEnElArea }
    requirements:
        accion: otrosLugaresEnElArea

_lugarYaExiste:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:lugarYaExiste }
    requirements:
        accion: lugarYaExiste

_filtroDeLugares:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:filtroDeLugares }
    requirements:
        accion: filtroDeLugares

_sugerirUnLugar:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:sugerirUnLugar }
    requirements:
        accion: sugerirUnLugar

_recomendarCalle:
    pattern: /ajax/recomendarCalle
    defaults: { _controller: LoogaresLugarBundle:Ajax:recomendarCalle }

_moduloRecomendacion:
    pattern: /ajax/recomendacion
    defaults: { _controller: LoogaresLugarBundle:Ajax:recomendacion }

_util:
    pattern: /ajax/util
    defaults: { _controller: LoogaresLugarBundle:Ajax:util }

_utilMail:
    pattern: /ajax/util_mail
    defaults: { _controller: LoogaresLugarBundle:Ajax:utilMail }

_galeria:
    pattern: /lugar/{slug}/galeria
    defaults: { _controller: LoogaresLugarBundle:Lugar:galeria }

_agregarFotoLugar:
    pattern: /lugar/{slug}/galeria/agregar
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregarFoto }

_editarFotoLugar:
    pattern: /lugar/{slug}/galeria/{id}/editar
    defaults: { _controller: LoogaresLugarBundle:Lugar:editarFoto }

_eliminarFotoLugar:
    pattern: /lugar/{slug}/galeria/{id}/borrar
    defaults: { _controller: LoogaresLugarBundle:Lugar:eliminarFoto }

_fotoGaleria:
    pattern: /lugar/{slug}/galeria/{id}
    defaults: { _controller: LoogaresLugarBundle:Lugar:fotoGaleria }

_paginaGaleria:
    pattern: /ajax/galeria/{id}/pagina
    defaults: { _controller: LoogaresLugarBundle:Ajax:paginaGaleria }

_recomienda:
    pattern: /lugar/{slug}/recomienda
    defaults: { _controller: LoogaresLugarBundle:Lugar:recomendaciones }

_recomendacion:
    pattern: /lugar/{slug}/recomendacion/{usuarioSlug}
    defaults: { _controller: LoogaresLugarBundle:Lugar:lugar }

_borrarRecomendacion:
    pattern: /lugar/{slug}/recomendacion/borrar
    defaults: { _controller: LoogaresLugarBundle:Lugar:accionRecomendacion, borrar: true}

_reportarLugar:
    pattern: /lugar/{slug}/reportar
    defaults: { _controller: LoogaresLugarBundle:Lugar:reportarLugar }
_reportarFoto:
    pattern: /lugar/{slug}/galeria/{id}/reportar
    defaults: { _controller: LoogaresLugarBundle:Lugar:reportarFoto }
_reportarRecomendacion:
    pattern: /lugar/{slug}/recomendacion/{usuarioSlug}/reportar
    defaults: { _controller: LoogaresLugarBundle:Lugar:reportarRecomendacion }
_reclamarLugar:
    pattern: /lugar/{slug}/dueno
    defaults: { _controller: LoogaresLugarBundle:Lugar:reclamarLugar }
_enviarLugar:
    pattern: /lugar/{slug}/enviar
    defaults: { _controller: LoogaresLugarBundle:Lugar:enviarLugar }
_enviarRecomendacion:
    pattern: /lugar/{slug}/recomendacion/{usuarioSlug}/enviar
    defaults: { _controller: LoogaresLugarBundle:Lugar:enviarRecomendacion }



#
# NAVEGACION
#
_buscar:
    pattern: /{slug}/buscar/{term}
    defaults: {_controller: LoogaresLugarBundle:Search:buscar, esBusqueda: true, term: false }
_categoria:
    pattern: /{slug}/categoria/{term}
    defaults: { _controller: LoogaresLugarBundle:Search:buscar, esBusqueda: false, esCategoria: true}
_subcategoria:  
    pattern: /{slug}/sub-categoria/{term}
    defaults: { _controller: LoogaresLugarBundle:Search:buscar, esBusqueda: false, esSubCategoria:true}
_tags:
    pattern: /{slug}/tags/{term}
    defaults: { _controller: LoogaresLugarBundle:Search:buscar, esBusqueda: false, esTag: true }
_comuna:
    pattern: /{slug}/comuna/{term}
    defaults: { _controller: LoogaresLugarBundle:Search:buscar, esBusqueda: false, esComuna: true }
_sector:
    pattern: /{slug}/sector/{term}
    defaults: { _controller: LoogaresLugarBundle:Search:buscar, esBusqueda: false, esSector: true }