LoogaresLugarBundle_homepage:
    pattern:  /agregar
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregar }

_listado:
    pattern: /listado
    defaults: { _controller: LoogaresLugarBundle:Lugar:listado }

_agregar:
    pattern: /lugar/agregar
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregar }

_lugar:
    pattern: /lugar/{slug}
    defaults: { _controller: LoogaresLugarBundle:Lugar:lugar }

_editar:
    pattern: /lugar/editar/{slug}
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregar }

_ajax:
    pattern: /ajax
    defaults: { _controller: LoogaresLugarBundle:Default:index }

_otrosLugaresEnElArea:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:otrosLugaresEnElArea }
    requirements:
        accion: otrosLugaresEnElArea

_lugarYaExiste:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:lugarYaExiste }
    requirements:
        accion: lugarYaExiste

_filtroDeLugares:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:filtroDeLugares }
    requirements:
        accion: filtroDeLugares

_sugerirUnLugar:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:sugerirUnLugar }
    requirements:
        accion: sugerirUnLugar

_recomendarCalle:
    pattern: /ajax/recomendarCalle
    defaults: { _controller: LoogaresLugarBundle:Ajax:recomendarCalle }

_agregarFotoLugar:
    pattern: /lugar/{slug}/galeria/agregar
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregarFoto }

_editarFotoLugar:
    pattern: /lugar/{slug}/galeria/{id}/editar
    defaults: { _controller: LoogaresLugarBundle:Lugar:editarFoto }

_eliminarFotoLugar:
    pattern: /lugar/{slug}/galeria/{id}/borrar
    defaults: { _controller: LoogaresLugarBundle:Lugar:eliminarFoto }
