LoogaresLugarBundle_homepage:
    pattern:  /agregar
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregar }

_listado:
    pattern: /listado
    defaults: { _controller: LoogaresLugarBundle:Lugar:listado }

_agregar:
    pattern: /lugar/agregar
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregar }

_lugar:
    pattern: /lugar/{slug}
    defaults: { _controller: LoogaresLugarBundle:Lugar:lugar }

_ajax:
    pattern: /ajax
    defaults: { _controller: LoogaresLugarBundle:Default:index }

_otrosLugaresEnElArea:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:otrosLugaresEnElArea }
    requirements:
        accion: otrosLugaresEnElArea

_filtroDeLugares:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:filtroDeLugares }
    requirements:
        accion: filtroDeLugares

_sugerirUnLugar:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:sugerirUnLugar }
    requirements:
        accion: sugerirUnLugar

_otrosLugaresEnElArea:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:generarComunasPorCiudad }
    requirements:
        accion: generarComunasPorCiudad