LoogaresLugarBundle_homepage:
#    pattern:  /agregar
    locales:
        es : /agregar
        en : /add
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregar }

_agregar:
    locales:
        es : /lugar/agregar
        en : /place/add
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregar }

_lugar:
    locales:
        es : /lugar/{slug}
        en : /place/{slug}
    pattern:
    defaults: { _controller: LoogaresLugarBundle:Lugar:lugar}

_editar:
    locales:
        es : /lugar/{slug}/editar
        en : /place/{slug}/edit
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregar }

_lugaresGeoJSON:
    locales:
        es: /ajax/geo/lugares
        en: /ajax/geo/places
    defaults: { _controller: LoogaresLugarBundle:Ajax:lugaresGeoJSON}

_otrosLugaresEnElArea:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:otrosLugaresEnElArea }
    requirements:
        accion: otrosLugaresEnElArea

_lugarYaExiste:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:lugarYaExiste }
    requirements:
        accion: lugarYaExiste

_filtroDeLugares:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:filtroDeLugares }
    requirements:
        accion: filtroDeLugares

_sugerirUnLugar:
    pattern: /ajax/{accion}
    defaults: { _controller: LoogaresLugarBundle:Ajax:sugerirUnLugar }
    requirements:
        accion: sugerirUnLugar

_recomendarCalle:
    locales:
        es: /ajax/recomendar-calle
        en: /ajax/review-street
    defaults: { _controller: LoogaresLugarBundle:Ajax:recomendarCalle }

_moduloRecomendacion:
    locales:
        es: /ajax/recomendacion
        en: /ajax/review
    defaults: { _controller: LoogaresLugarBundle:Ajax:recomendacion }

_util:
    locales:
        es: /ajax/accion
        en: /ajax/action
    defaults: { _controller: LoogaresLugarBundle:Ajax:accion }

_utilMail:
    pattern: /ajax/util_mail
    defaults: { _controller: LoogaresLugarBundle:Ajax:utilMail }

_cuponesCanjeados:
    locales:
        es: /ajax/cupones_canjeados
        en: /ajax/payed_coupons
    defaults: { _controller: LoogaresLugarBundle:Ajax:cuponesCanjeados }

_galeria:
    locales:
        es: /lugar/{slug}/galeria
        en: /place/{slug}/gallery
    defaults: { _controller: LoogaresLugarBundle:Lugar:galeria }

_agregarFotoLugar:
    locales:
        es: /lugar/{slug}/galeria/agregar
        en: /place/{slug}/gallery/add
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregarFoto }

_editarFotoLugar:
    locales:
        es: /lugar/{slug}/galeria/{id}/editar
        en: /place/{slug}/gallery/{id}/edit
    defaults: { _controller: LoogaresLugarBundle:Lugar:editarFoto }

_eliminarFotoLugar:
    locales:
        es: /lugar/{slug}/galeria/{id}/borrar
        en: /place/{slug}/gallery/{id}/delete
    defaults: { _controller: LoogaresLugarBundle:Lugar:eliminarFoto }

_fotoGaleria:
    locales:
        es: /lugar/{slug}/galeria/{id}
        en: /place/{slug}/gallery/{id}
    defaults: { _controller: LoogaresLugarBundle:Lugar:fotoGaleria }

_paginaGaleria:
    locales:
        es: /ajax/galeria/{id}/pagina
        en: /ajax/gallery/{id}/page
    defaults: { _controller: LoogaresLugarBundle:Ajax:paginaGaleria }

_recomienda:
    locales:
        es: /lugar/{slug}/recomienda
        en: /places/{slug}/reviewit
    defaults: { _controller: LoogaresLugarBundle:Lugar:recomendaciones }

_borrarRecomendacion:
    locales:
        es: /lugar/{slug}/recomendacion/borrar
        en: /place/{slug}/review/delete
    defaults: { _controller: LoogaresLugarBundle:Lugar:accionRecomendacion, borrar: true}

_lugarRecomendacion:
    locales:
        es: /lugar/{slug}/recomendacion
        en: /place/{slug}/review
    defaults: { _controller: LoogaresLugarBundle:Lugar:lugarRecomendacion}

_recomendacion:
    locales:
        es: /lugar/{slug}/recomendacion/{usuarioSlug}
        en: /place/{slug}/review/{usuarioSlug}
    defaults: { _controller: LoogaresLugarBundle:Lugar:lugarRecomendacion}

_lugarMapa:
    locales:
        es: /lugar/{slug}/mapa
        en: /place/{slug}/map
    defaults: { _controller: LoogaresLugarBundle:Lugar:lugarMapa}

_reportarLugar:
    locales:
        es: /lugar/{slug}/reportar
        en: /place/{slug}/report
    defaults: { _controller: LoogaresLugarBundle:Lugar:reportarLugar }

_reportarFoto:
    locales:
        es: /lugar/{slug}/galeria/{id}/reportar
        en: /place/{slug}/gallery/{id}/report
    defaults: { _controller: LoogaresLugarBundle:Lugar:reportarFoto }

_reportarRecomendacion:
    locales:
        es: /lugar/{slug}/recomendacion/{usuarioSlug}/reportar
        en: /place/{slug}/review/{usuarioSlug}/report
    defaults: { _controller: LoogaresLugarBundle:Lugar:reportarRecomendacion }

_reclamarLugar:
    locales:
        es: /lugar/{slug}/dueno
        en: /place/{slug}/owner
    defaults: { _controller: LoogaresLugarBundle:Lugar:reclamarLugar }

_enviarLugar:
    locales:
        es: /lugar/{slug}/enviar
        en: /place/{slug}/send
    defaults: { _controller: LoogaresLugarBundle:Lugar:enviarLugar }

_enviarRecomendacion:
    locales:
        es: /lugar/{slug}/recomendacion/{usuarioSlug}/enviar
        en: /place/{slug}/review/{usuarioSlug}/send
    defaults: { _controller: LoogaresLugarBundle:Lugar:enviarRecomendacion }

_pedidosLugar:
    locales:
        es: /lugar/{slug}/{tipo}
        en: /place/{slug}/{tipo}
    defaults: { _controller: LoogaresLugarBundle:Lugar:pedidosLugar }
    requirements:
# @todo Traduccion reservas/pedidos
        tipo: reservas|pedidos

#
# NAVEGACION
#

_buscar:
    locales:
        es: /{slug}/buscar
        en: /{slug}/search
    defaults: { _controller: LoogaresLugarBundle:Search:buscar, path: _buscar }

_categoria_subcategoria_sector:
    locales:
        es: /{slug}/sector/{sector}/categoria/{categoria}/{subcategoria}
        en: /{slug}/neighborhood/{sector}/category/{categoria}/{subcategoria}
    defaults: { _controller: LoogaresLugarBundle:Search:buscar, path: _categoria_subcategoria }

_categoria_subcategoria_comuna:
    locales:
        es: /{slug}/comuna/{comuna}/categoria/{categoria}/{subcategoria}
        en: /{slug}/county/{comuna}/category/{categoria}/{subcategoria}
    defaults: { _controller: LoogaresLugarBundle:Search:buscar, path: _categoria_subcategoria }

_categoria_subcategoria:
    locales:
        es: /{slug}/categoria/{categoria}/{subcategoria}
        en: /{slug}/category/{categoria}/{subcategoria}
    defaults: { _controller: LoogaresLugarBundle:Search:buscar, path: _categoria_subcategoria }

_categoria_sector:
    locales:
        es: /{slug}/sector/{sector}/categoria/{categoria}
        en: /{slug}/neighborhood/{sector}/category/{categoria}
    defaults: { _controller: LoogaresLugarBundle:Search:buscar, path: _categoria }

_categoria_comuna:
    locales:
        es: /{slug}/comuna/{comuna}/categoria/{categoria}
        en: /{slug}/county/{comuna}/category/{categoria}
    defaults: { _controller: LoogaresLugarBundle:Search:buscar, path: _categoria }

_categoria_sola:
    locales:
        es: /{slug}/categoria
        en: /{slug}/category
    defaults: { _controller: LoogaresLugarBundle:Search:categoria, path: _categoria }

_categoria:
    locales:
        es: /{slug}/categoria/{categoria}
        en: /{slug}/category/{categoria}
    defaults: { _controller: LoogaresLugarBundle:Search:buscar, path: _categoria }

_subcategoria:
    locales:
        es: /{slug}/subcategoria/{subcategoria}
        en: /{slug}/subcategory/{subcategoria}
    defaults: { _controller: LoogaresLugarBundle:Search:subcategoria, path: _subcategoria }

_comuna:
    locales:
        es: /{slug}/comuna/{term}
        en: /{slug}/county/{term}
    defaults: { _controller: LoogaresLugarBundle:Search:buscar, esBusqueda: false, esComuna: true }

_sector:
    locales:
        es: /{slug}/sector/{term}
        en: /{slug}/heighborhood/{term}
    defaults: { _controller: LoogaresLugarBundle:Search:buscar, esBusqueda: false, esSector: true }