Loogares\LugarBundle\Entity\Lugar:
    properties:
        nombre:
            - NotBlank:
                message:  ;o

Loogares\LugarBundle\Entity\ImagenLugar:
    properties:
        firstImg:
            - Image:
                maxSize: 5120k
                mimeTypesMessage: Sólo JPG, GIF y PNG, máx. 5 MB.

        secondImg:
            - Image:
                maxSize: 5120k
                mimeTypesMessage: Sólo JPG, GIF y PNG, máx. 5 MB.

        thirdImg:
            - Image:
                maxSize: 5120k
                mimeTypesMessage: Sólo JPG, GIF y PNG, máx. 5 MB.