LoogaresAdminBundle_lugares:
    pattern:  /lugares
    defaults: { _controller: LoogaresAdminBundle:Default:lugares }

LoogaresAdminBundle_usuarios:
    pattern:  /usuarios
    defaults: { _controller: LoogaresAdminBundle:Default:usuarios }

LoogaresAdminBundle_lugaresAEditar:
    pattern:  /lugares/revision
    defaults: { _controller: LoogaresAdminBundle:Default:lugaresAEditar }

LoogaresAdminBundle_revisionLugar:
    pattern:  /lugares/revision/{slug}
    defaults: { _controller: LoogaresAdminBundle:Default:revisionLugares }

LoogaresAdminBundle_editarLugar:
    pattern:  /lugares/editar/{slug}/{id}
    defaults: { _controller: LoogaresLugarBundle:Lugar:agregar, id: null, isAdmin: true }

LoogaresAdminBundle_index:
    pattern:  /
    defaults: { _controller: LoogaresAdminBundle:Default:index }