LoogaresAdminBundle_usuarios:
    pattern:  /usuarios
    defaults: { _controller: LoogaresAdminBundle:Admin:usuarios }


LoogaresAdminBundle_index:
    pattern:  /
    defaults: { _controller: LoogaresAdminBundle:Admin:index }

LoogaresAdminBundle_seleccionarPais:
    pattern:  /lugares
    defaults: { _controller: LoogaresAdminBundle:Admin:seleccionarPais }

LoogaresAdminBundle_administrarLugares:
    pattern: /lugares/{ciudad}
    defaults: { _controller: LoogaresAdminBundle:Admin:administrarLugares }

LoogaresAdminBundle_listadoLugares:
    pattern:  /lugares/{ciudad}/listado
    defaults: { _controller: LoogaresAdminBundle:Admin:listadoLugares }

LoogaresAdminBundle_listadoRevision:
    pattern:  /lugares/{ciudad}/revision/listado
    defaults: { _controller: LoogaresAdminBundle:Admin:listadoRevision }

LoogaresAdminBundle_revisionLugar:
    pattern:  /lugares/{ciudad}/revision/{slug}
    defaults: { _controller: LoogaresAdminBundle:Admin:revisionLugares }