LoogaresAdminBundle_index:
    pattern:  /
    defaults: { _controller: LoogaresAdminBundle:Admin:index }
LoogaresAdminBundle_sugerirLugar:
    pattern:  /ajax/sugerirLugar
    defaults: { _controller: LoogaresAdminBundle:AdminAjax:sugerirLugar }

#
#
#Rutas del Adminsitrador de Recomendaciones
#
#
LoogaresAdminBundle_listadoRecomendaciones:
    pattern: /lugares/{ciudad}/recomendaciones
    defaults: {_controller: LoogaresAdminBundle:Admin:listadoRecomendaciones}

LoogaresAdminBundle_borrarRecomendacion:
    pattern: /lugares/{ciudad}/recomendaciones/borrar/{id}
    defaults: {_controller: LoogaresAdminBundle:Admin:accionRecomendaciones, habilitar: false, borrar: true}

LoogaresAdminBundle_habilitarRecomendacion:
    pattern: /lugares/{ciudad}/recomendaciones/aprobar/{id}
    defaults: {_controller: LoogaresAdminBundle:Admin:accionRecomendaciones, habilitar: true, borrar: false}

LoogaresAdminBundle_editarRecomendacion:
    pattern: /lugares/{ciudad}/recomendaciones/editar/{id}
    defaults: {_controller: LoogaresAdminBundle:Admin:editarRecomendacion }

#
#
#Rutas del Administrador de Imagenes
#
#
LoogaresAdminBundle_aprobarFoto:
    pattern:  /lugares/{ciudad}/{slug}/fotos/aprobar
    defaults: { _controller: LoogaresAdminBundle:Admin:accionFotos, aprobar: true, borrar: false }
LoogaresAdminBundle_borrarFoto:
    pattern:  /lugares/{ciudad}/{slug}/fotos/borrar
    defaults: { _controller: LoogaresAdminBundle:Admin:accionFotos, aprobar: false, borrar: true }
LoogaresAdminBundle_accionFotos:
    pattern:  /lugares/{ciudad}/{slug}/fotos/massive
    defaults: { _controller: LoogaresAdminBundle:Admin:accionFotos, aprobar: false, borrar: false }
LoogaresAdminBundle_editarFoto:
    pattern:  /lugares/{ciudad}/{slug}/fotos/editar/{id}
    defaults: { _controller: LoogaresAdminBundle:Admin:editarFoto }

#
#
#Rutas del Administrador de Usuario
#
#
LoogaresAdminBundle_listadoUsuarios:
    pattern:  /usuarios
    defaults: { _controller: LoogaresAdminBundle:Admin:listadoUsuarios }

LoogaresAdminBundle_desactivarUsuario:
    pattern:  /usuarios/desactivar/{id}
    defaults: { _controller: LoogaresAdminBundle:Admin:accionUsuario, desactivar: true, activar: false }

LoogaresAdminBundle_activarUsuario:
    pattern:  /usuarios/activar/{id}
    defaults: { _controller: LoogaresAdminBundle:Admin:accionUsuario, desactivar: false, activar: true }

LoogaresAdminBundle_accionUsuario:
    pattern:  /usuarios/massive
    defaults: { _controller: LoogaresAdminBundle:Admin:accionUsuario, desactivar: false, activar: false }

#
#
#Rutas del Administrador de Lugar
#
#

LoogaresAdminBundle_seleccionarPais:
    pattern:  /lugares
    defaults: { _controller: LoogaresAdminBundle:Admin:seleccionarPais }

LoogaresAdminBundle_administrarLugares:
    pattern: /lugares/{ciudad}
    defaults: { _controller: LoogaresAdminBundle:Admin:administrarLugares }

LoogaresAdminBundle_listadoLugares:
    pattern:  /lugares/{ciudad}/listado
    defaults: { _controller: LoogaresAdminBundle:Admin:listadoLugares }

LoogaresAdminBundle_listadoRevision:
    pattern:  /lugares/{ciudad}/revision/listado
    defaults: { _controller: LoogaresAdminBundle:Admin:listadoRevision }

LoogaresAdminBundle_revisionLugar:
    pattern:  /lugares/{ciudad}/revision/{slug}
    defaults: { _controller: LoogaresAdminBundle:Admin:revisionLugares }

LoogaresAdminBundle_borrarLugar:
    pattern:  /lugares/{ciudad}/revision/borrar/{id}
    defaults: { _controller: LoogaresAdminBundle:Admin:accionLugar, cerrar: false, habilitar: false, borrar: true  }

LoogaresAdminBundle_cerrarLugar:
    pattern:  /lugares/{ciudad}/revision/cerrar/{id}
    defaults: { _controller: LoogaresAdminBundle:Admin:accionLugar, cerrar: true, habilitar: false, borrar: false}

LoogaresAdminBundle_habilitarLugar:
    pattern:  /lugares/{ciudad}/revision/habilitar/{id}
    defaults: { _controller: LoogaresAdminBundle:Admin:accionLugar, cerrar: false, habilitar: true, borrar: false }

LoogaresAdminBundle_accionLugar:
    pattern:  /lugares/{ciudad}/revision/massive/
    defaults: { _controller: LoogaresAdminBundle:Admin:accionLugar, cerrar: false, habilitar: false, borrar: false}

LoogaresAdminBundle_fotosLugar:
    pattern:  /lugares/{ciudad}/{slug}/fotos
    defaults: { _controller: LoogaresAdminBundle:Admin:fotosLugar }

LoogaresAdminBundle_pedidosLugar:
    pattern:  /lugares/{ciudad}/{slug}/pedidos
    defaults: { _controller: LoogaresAdminBundle:Admin:pedidosLugares }


_test_mail:
    pattern:  /test/mail
    defaults: { _controller: LoogaresAdminBundle:Admin:testMail }


#
#
#Rutas del Administrador de Pedidos
#
#
LoogaresAdminBundle_accionPedidos:
    pattern:  /lugares/{ciudad}/{slug}/pedidos/massive
    defaults: { _controller: LoogaresAdminBundle:Admin:accionPedidos, aprobar: false, borrar: false }
LoogaresAdminBundle_editarPedido:
    pattern:  /lugares/{ciudad}/{slug}/pedidos/editar/{id}
    defaults: { _controller: LoogaresAdminBundle:Admin:editarPedido }
LoogaresAdminBundle_borrarPedido:
    pattern:  /lugares/{ciudad}/{slug}/pedidos/borrar/{id}
    defaults: { _controller: LoogaresAdminBundle:Admin:borrarPedido }
LoogaresAdminBundle_borrarPromocion:
    pattern:  /lugares/{ciudad}/{slug}/pedidos/borrar/{id}/promocion
    defaults: { _controller: LoogaresAdminBundle:AdminAjax:borrarPromocion }
