LoogaresAdminBundle_lugares:
    pattern:  /lugares
    defaults: { _controller: LoogaresAdminBundle:Default:lugares }

LoogaresAdminBundle_usuarios:
    pattern:  /usuarios
    defaults: { _controller: LoogaresAdminBundle:Default:usuarios }

LoogaresAdminBundle_index:
    pattern:  /
    defaults: { _controller: LoogaresAdminBundle:Default:index }
