Loogares\CampanaBundle\Entity\Descuento:
    type: entity
    table:  descuentos
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        condiciones:
            type: string
        fecha_inicio:
            type: datetime
        fecha_termino:
            type: datetime
        cantidad:
            type: integer