LoogaresPhoneBundle_categorias:
    pattern:  /api/categorias
    defaults: { _controller: LoogaresPhoneBundle:Default:listadoCategorias, _format: json}
    requirements:
        _format:  json

LoogaresPhoneBundle_categoria:
    pattern:  /api/categoria/{ciudad}/{categoria}/{offset}/{latitude}/{longitude}
    defaults: { _controller: LoogaresPhoneBundle:Default:lugaresPorCategoria, _format: json, categoria: todas, offset: 1, latitude: null, longitude: null}
    requirements:
        _format:  json

LoogaresPhoneBundle_lugar:
    pattern: /api/lugar/{slug}
    defaults: { _controller: LoogaresPhoneBundle:Default:lugar, _format: json }
    requirements:
        _format: json

LoogaresPhoneBundle_quickSearch:
    pattern: /api/qs/{slug}/{term}
    defaults: { _controller: LoogaresPhoneBundle:Default:quickSearch, _format: json }
    requirements:
        _format: json

LoogaresPhoneBundle_search:
    pattern: /api/s/{slug}
    defaults: { _controller: LoogaresPhoneBundle:Default:search, _format: json }
    requirements:
        _format: json