parameters:
#    loogares_mail.example.class: Loogares\MailBundle\Example

services:
#    loogares_mail.example:
#        class: %loogares_mail.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
